= Step 1. Prerequisites for Building an API-Led Solution

Before you begin building your API-led solution, verify that you have the required tools and access:

* Username and password for your Anypoint Platform organization. If you don't have Anypoint Platform yet, create a Trial organization on Anypoint Platform.
+
link:https://anypoint.mulesoft.com/login/#/signup["Create a Trial organization^", role="button-primary"]

* xref:anypoint-code-builder::start-acb-desktop.adoc[Set up Anypoint Code Builder]. 
* To test REST requests, obtain a client such as Advanced REST Client or Postman if you don't already have one. This tutorial Postman.
+
link:https://www.postman.com/downloads/["Install Postman^", role=button-primary"]
+
Depending on your platform, you might need to install a different client.

* Required Permissions:
** *Design Center Developer*
+
Allows API specification creation
** *Exchange Contributor*
+
Enables publishing assets to Exchange
** *CloudHub 2.0 Deploy*
+
Allows deployment to CloudHub 2.0

* Optional Permissions (for MuleSoft Vibes AI features):
** *Mule Developer Generative AI User*
+
Enables MuleSoft Vibes features for AI-generated API specifications. If you don't have this permission, you can still complete the tutorial by manually creating your API specification.
+
*MuleSoft Vibes* requires Agentforce to be enabled in Access Management. See xref:access-management::enabling-agentforce.adoc[].

== CloudHub 2.0 Setup

For CloudHub 2.0 deployments, you need:

* A CloudHub 2.0 Shared Space in your organization. Anypoint Platform trial accounts include a default Shared Space.
+
See xref:cloudhub-2::ch2-shared-space-about.adoc[About Shared Spaces].

* At least one environment (such as Sandbox or Development) configured for CloudHub 2.0 deployments.
+
See xref:cloudhub-2::ch2-environments-about.adoc[About Environments].

== Helpful Hints

* Use two browser windows: One to read instructions and one to perform the tasks.

* In Anypoint Code Builder, enable auto-save to avoid losing work (*File > Auto Save*).

* Bookmark the https://anypoint.mulesoft.com[Anypoint Platform] login page.

== What's Next

With your environment ready, you'll use MuleSoft Vibes to design your first API specification using natural language prompts.

xref:api-led-design-acb.adoc[Next: Design an API Specification]
