= Anypoint Platform Compatibility Support for Restful-APIs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can design an API in Anypoint Platform using a RESTful API Modeling Language (RAML) or an OpenAPI Specification (OAS) format based on your needs. Both RAML and OAS specifications implement an almost-RESTful API model and provide the same features, except for the callback support in OAS 3.0. 

RAML, which is optimized for design and reusability, implements _syntactic sugar_ to make descriptions smaller. Conversely, OAS enables you to simulate the components and libraries.

MuleSoft API Tooling, which includes parser AMF and Language server (ALS), provides interoperability using common metadata model and enables data definition reuse, use of linting rules, and provides translation in both RAML and OAS specifications.

Before you start designing an API, learn more about how each of the specification features are implemented in Anypoint Platform products:

* xref:api-spec-support-api-designer.adoc[API Specifications Support in API Designer]
//* xref:api-spec-support-api-designer.adoc[check]


