= Build an API Tutorial: Design an API Specification
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To design an API, assess the purpose and requirements:

* Identify the type of API. Is it a simple API, part of an integration, or part of a back-end system?
* Understand the data flows: one-way, two-way, or more.
* Explore the security requirements.

After you define the scope and flow of your integration project,
define an API specification in RAML (or import to RAML from OAS).
Then, in later steps, you'll use the API specification to quickly develop an API.  

== API Specifications and APIs
An API is a published interface to a resource that anyone with the correct permissions
and a properly structured request can access. 

An API specification details the functional and expected behavior of an API, 
as well as the fundamental design philosophy and supported data types.
It contains both documentation and API definitions 
to create a contract that people and software can read. 

MuleSoft provides tools that make it easy to create an API specification that you can then share with your team, your customers, or the general public.
The API specification increases adoption and speeds up project completion. 

== Step 1: Explore Existing API Specifications
If you look at existing API specifications before writing your own,
you can learn how other people have approached situations similar to yours.
You can also check whether an API specification with the same objectives is not already in development, and reuse it if appropriate.

Looking for an API specification that already does what you need is easy:

* Look at the public Exchange. You’ll see some of the most popular API specifications, connectors, and other assets displayed.
+
link:https://www.mulesoft.com/exchange["Take me there^", role="button-primary"]
 +
Select *REST APIs* from the *Type* dropdown to display only REST API specifications. Click on any specification to see the data types and the HTTP requests defined for the API. 
+
* To look at just the items in Exchange for your organization (account), 
log in to Anypoint Platform.
+
link:https://anypoint.mulesoft.com/login["Take me there^", role="button-primary"] 

After exploring Exchange, return to Anypoint Platform to create a new API specification that defines what our tutorial API can do.

== Step 2: Create Your API Specification

In link:https://anypoint.mulesoft.com/login/["Anypoint Platform^", role="button-primary"]:

. Click the blue button under Design Center to open API Designer.
. Click *Create* to open the API Designer editor.
. Click *Create API specification*.
. Enter `Hello-World` for *Name* and leave the other default values.
. Click *Create Specification*.
. The API Designer editor displays a sample RAML definition. Replace it with RAML that specifies the API:

[source,raml]
----
#%RAML 1.0
title: Hello, World
version: v1
description: A greeting for the world

securitySchemes:
 basic:
   description: |
     This API supports Basic Authentication.
   type: Basic Authentication
 
securedBy: [basic]

types:
 greeting: # <2>
   properties:
     todays-greeting: string

/greeting:
 /{todays-greeting}:
     uriParameters:
       todays-greeting: string
     get: # <1>
       responses: # <3>
         200:
           body:
             application/json:
               type: greeting
         404: # <4>
           body:
             application/json:
               properties:
                 message: string
               example: |
                 {
                   "message" : "Greeting not found"
                 }
----
<1> A single HTTP request, GET
<2> A single `dataType`, `greeting`, with a single property, `todays-greeting` 
<3> HTTP response
<4> Error message and error handling

== Step 3: Test Your API Specification
The API specification `hello-world.raml` is complete. Now test it by sending a request.
The mocking service creates a functioning endpoint from your API specification
and provides a simple UI for managing authentication, request headers, and response headers.

To test the API specification:

. link:https://anypoint.mulesoft.com/designcenter/#/projects["Open `hello-world.raml`.^" role="button-primary"]
. Click the X next to *Mocking service* to enable the mocking service. If you see a checkmark instead of an X, the mocking service is already enabled.
. Inspect the *API endpoints* that you defined. HTTP requests appear in green boxes.
. Click *GET* to display the GET endpoint.
. Review the *Code examples* for each protocol.
. Review the *Security* section. *Basic Authentication* is the only option for this API; normally others would be available here.
. Click *Try it*.
. Enter values in the Authorization and Parameters tabs: 
  .. In the Authorization tab, enter the *User name* and *Password* needed to access this endpoint. In this example, you can enter any string.
  .. In the Parameters tab, enter a value for *todays-greeting*: `The greeting for today is Hello.`. 
. Click *Send* to send your request to the temporary request URL that the mocking service creates from your specification. If the request is successful, you’ll see `*HTTP message 200 OK*`. 
. Click *Details* to examine the response headers and request headers in the mocking service to help diagnose issues or understand the behavior of your API specification.
. When you have finished testing, click the mocking service checkmark to exit.

== Step 4. Publish Your API Specification
After you have tested your API, publish it to your private Exchange so others in your organization can reuse your work.

. link:https://anypoint.mulesoft.com/designcenter/#/projects["Open `hello-world.raml`.^" role="button-primary"]
. Click *Publish*.
. Click *Publish to Exchange*. 

After publication, anyone in your organization can see the Hello-World API specification and reuse it.

== What’s Next

Now that you have designed an API and created an API specification for it, 
use Anypoint Studio (Studio) to create a Mule app that contains the implementation and interface for the API.

== Developer Deep Dives

If you're curious about the details, dive right in.

=== Deep Dive: Exchange

You can publish assets to the public Exchange, your internal exchange, or your public developer portal.

* In addition to the public Exchange, you can review your own organization’s internal offerings.
+
link:https://anypoint.mulesoft.com/exchange/["Take me to Exchange^", role="button-primary"]
+
* If you've created a public developer portal, you can look there as well; click *Public portal*.

=== Deep Dive: Creating an API Specification

In a typical API project, you’d likely want to do a few more things:

* Add annotations.
+
link:https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#annotations["Take me to the RAML specification^", role="button-primary"]
* xref:design-center::design-import-files.adoc[Add assets from Exchange using API Designer or Studio.]
* xref:studio::import-api-specification-design-center.adoc[Model the data your API specification exposes, using Studio.]
* xref:design-center::design-create-publish-api-fragment.adoc[Modularize your specifications for reuse with API fragments.]

=== Developer and Partner Deep-Dive
To share and support your API specification, collect feedback about your API specification for xref:exchange::to-change-raml-version.adoc[the next version]. 
