= API-Led Connectivity: Develop and Test the API
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Now that you have created an API specification, you can build and test the API you plan to deploy.
We'll build the business logic into an implementation XML file, and then import the API specification
to take advantage of the automated scaffolding that Studio and APIkit provide, in order to complete the API interface.

Finally, we'll add unit tests and test the API all from Studio.

== 2.1 Build the API

You've created an API specification--now it's time to create the API (or connect to an existing one using the information in the specification).
In MuleSoft, you package the business logic (implementation) and the interface in an application that is deployed to a Mule runtime engine instance.

The steps in this section assume you have launched Studio before each Step.

=== Step 1: Add Your Anypoint Platform Credentials to Studio

Add your Anypoint Platform credentials in Studio once, and they'll be available for all the projects you create.

. In Studio, open the *Preferences* dialog.
. Select *Anypoint Studio > Authentication*.
. Enter your Anypoint Platform username and password.
. Click *Sign in*.
. Click *Apply and Close*.

These credentials are available for the duration indicated when you entered them, seven days by default.

=== Step 2: Create a New Project

To deploy an API to the Mule runtime engine in the target of your choice, 
build the interface and implementation in a Mule app using Studio. In this step,
we'll create the project.

. In Studio, select *File > New > Mule Project*.
. In the dialog box, provide the following values:
  ** *Project Name*: Hello-World
  ** *Runtime*: If there is a choice, select the latest version of Mule. This is the Mule runtime engine that is hosted within Studio for testing.

The Package Explorer displays the Mule project *hello-world*, and opens the main implementation (business logic)
XML file. We'll add some business logic in the next step.

=== Step 2: Find and Assemble Basic Elements

Find and assemble connectors, transformers, and choice routes to
define the business logic of your API:

. Add an HTTP connector endpoint to receive requests:
  .. In the *Mule Palette*, select *HTTP*, the HTTP module.
  .. Drag *Listener* from the *Mule Palette* to the canvas. This action creates a flow containing the listener.
. Specify the global properties that the Listener needs:
  .. Double-click HTTP Listener.
  .. In the General tab of the Listener properties, click the green Add button.
  .. In the Global Element Properties dialog, enter local host and port values:
    ... *Host*: 0.0.0.0
    ... *Port*: 8081
    ... Click *OK*.
  .. Return to the General tab of the Listener properties, and set *Path* to */greeting*, the resource we defined in the API specification.
  .. Save your changes.
. Specify logic to display the data from Hello World:
  .. Return to the *Mule Palette* and select *Favorites* or *Core* to display the *Set Payload* transformer.
  .. Find and drag *Set Payload* into the flow and leave it selected.
  .. In the *General* tab, set *Value* under *Settings* to *Today's greeting*. This value is for testing; you'll replace it later.
. Review the XML generated by your work in *Configuration XML*, and then return to *Message Flow*.

You have created a simple Mule app with some business logic.
Studio provides a Mule runtime engine in which you can deploy and run your app for testing.

To run the app:
. Right-click anywhere on the canvas and select *run project Hello World*.
. The console opens and displays status messages as the app is deployed.
. To exercise the app, open a REST client (Postman) and issue a GET request:
* Log Mule event messages
* Structure Mule applications using flows, subflows, asynchronous queues, properties files, and configuration files
* Define and manage application metadata (schemas)
* Implement KPIs for real-time insights (Mule Operational Analytics capability)
* Conditionally route events, validate events, and handle messaging errors
* <<Does this belong after add the api interface?>> Add unit tests

=== Step 3: Add the API Interface

To generate project scaffolding for your API, import Hello-World API specification into a new Studio project.
Once complete, you'll deploy your project as a Mule app to your target environment. The Mule app contains the interface and implementation of your API.

Create the API interface from your Hello World API specification, created in <link to topic>:

. Import Hello World API specification: <missing some steps>
  . Select *API Implementation* and *Scaffold selected API specifications*.
  . On the *Add API specification dependency* tab, click the plus sign.
  . Select *From Exchange* (Exchange for your Anypoint Platform organization). 
  . Verify that the username from Step 1 is displayed, then search for Hello in the search box.
  . Select *Hello-World* from *Available Modules*, then click *Add* to move it to *Selected modules*.
  . Click *Finish*.

== 2.2 Validate, Test, and Debug the Mule App

* Validate published assets for syntax and malicious files
* Test and debug functionality
* Validate enforcement of applied resource-based policies
* Add unit tests as errors are encountered

== 2.3 Publish the API Implementation

* Publish API implementation to Exchange
* Publish template, example, or reference integration to Exchange

== Developer Deep Dives

* Transform data with DataWeave