= Step 5. Deploy the API to CloudHub
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Now that you've created and tested the Mule app that contains your new API from
within Studio, let's deploy the API to CloudHub. First, we'll create an API proxy,
which then enables us to test the API from Exchange. We'll then set up policies and tiers of service,
and perform basic management tasks, such as approving or rejecting access.

??This topic will also explain the steps for securing an API that isn't deployed as a Mule app.??

=== Step 1: Deploy API to CloudHub

. From Studio, in the Mule Design perspective, right-click the `hello-world` project in Package Explorer,
and then select *Anypoint Platform > Deploy to CloudHub*.
. If prompted, enter your Anypoint Platform username and password and click *Sign in*.
. You must be in your account's sandbox to deploy the API:
  .. Click *Design* to launch the Switch Environment dialog.
  .. Click *Sandbox*.
  .. Click *Switch*.
. Enter `hello-world-greeting` or similar; every app and API name must be unique in the account.
. Verify that *Deployment Target* is `CloudHub`.
. Don't change any of the other default values.
. Click *Deploy Application*.

A window displays the status of the deployment. When you see a message that the
project has been successfully deployed, click *Close Window*.

To verify that the API works as expected:

. Open Runtime Manager.
+
link:https://anypoint.mulesoft.com/cloudhub/#/console/home/applications["Take me there^" role="button-primary"]
. In the Sandbox environment, click *Applications* and look for `hello-world-greeting`. It should show the `Started` status.
. To test the API deployment, send a request from Advanced Rest Client or a similar REST API tool:
  .. While still on the Applications page, click *hello-world-greeting* (but don't click the arrow next to the name).
  .. Copy the *App url* value. This is the base URI.
  .. In Advanced Rest Client or a similar REST API tool, send a request to the base URI that you just copied. Be sure to add the API endpoint `/greeting`: +
  
  GET +http://hello-world-greeting.us-w1.cloudhub.io/greeting

  .. If you see `200 OK` and the greeting you specified, `Today the greeting is Hello.`, then you have successfully deployed the API you created.

Now we need to create an API proxy application for this API, to restrict API access, keeping the service protected.
We'll add policies, specify service level agreement (SLA) tiers, and create monitoring alerts.
We can do this while the API is running.

=== Step 2: Create an API Proxy Application

In order to add a rate limit policy to our deployed API, we must first create an API proxy. 

. Log in to Anypoint Platform.
+
link:https://anypoint.mulesoft.com["Take me there^" "role=button-primary"]
. Click *API Manager*.
. Switch to the sandbox environment.
. Click *Manage API > Manage API from Exchange*.
. Enter `Hello` and select `Hello-World` from the drop-down.
. Verify the following values are selected:
  ** Asset type: RAML/OAS
  ** API version: v1
  ** Asset version: 1.0.1
  ** Managing type: Endpoint with Proxy
  ** Proxy deployment target: CloudHub
  ** Mule version: check the checkbox
  ** Implementation URI: `http://hello-world-greeting-us-w1.cloudhub.io/`. This is the same URI as you see in Runtime Manager for the API we created.
  ** You can ignore TLS context since our API simply returns a hard-coded value.
  ** Path: `/`
  ** Ignore Advanced options.
. Click *Save*.

API Manager shows you a status page for your new proxy. The status is *Unregistered* because we haven't deployed this proxy yet.

=== Step 3. Deploy the API Proxy

. To set deployment configuration options and deploy the new proxy:
  .. In the Deployment Configuration section, select *Runtime version: 4.2.2*.
  .. For *Proxy application name*, which is the name displayed in Runtime Manager, enter *hello-world-greeting-us-proxy*.
  .. Select *Update application if exists*.
  .. Click *Deploy*. 
. A progress window displays. You can view the logs as deployment progresses:
  .. After the *Starting application* stage, click *Click here*.
  .. Runtime Manager opens. Click *Logs*.
  .. Scroll through the log until you see `Your application has started successfully.`
. Provide a label and consumer endpoint for the proxy:
  .. Return to Anypoint Platform if you aren't already there:
+
link:https://anypoint.mulesoft.com/login["Take me there^", role="button-primary"] 
  .. Click *API Manager*.
  .. Hello-World is still active. Click *v1* to open the Hello-World v1 settings page.
  .. Click *Add a label*.
  .. Enter *No policy instance* and press Return to save the label.
  .. In the Proxy section, right-click the Proxy URL and copy the link.
  .. Back at the top of the API Manager settings page, click *Add consumer endpoint*.
  .. Paste in the link you just copied, and press Return to save the link.

. Now you can exercise the proxy endpoint from Exchange.
*THIS DOESN'T WORK with exchange or Advanced Rest Client. Why can't I just send /greeting, not /greeting/{todays message}?*
  .. Return to Exchange:
+
link:https://anypoint.mulesoft.com/exchange["Take me there^", role="button-primary"]
  .. Click Hello-World (REST API) to open it.
  .. On the left side, click */{todays-greeting}* to open it, then click *GET*.
  .. On the right side, toward the top of the column, click *Mocking Service* to open the drop-down menu.
  .. Select *Sandbox: No policy instance*

. Set your API to public on Exchange.
  .. link:https://anypoint.mulesoft.com/exchange["Take me there^", role="button-primary"]
  .. Select your API.
  .. Click *API Instances*.
  .. Set the *No policy instance*, the proxy you created, to *Public*.

=== Step 4: Add a Rate Limit Policy

To add a rate limit policy:

. Return to API Manager.
. Return to the *Settings* page for Hello-World API.
. In the navigation on the left, select *Policies*.
. Click *Apply New Policy*.
. Select the latest Mule version for your Mule version (4 or 3).
. Click *Configure Policy*.
. In the Apply Rate limiting policy page, set the limit values:
  ** *# of Reqs*: `3`
  ** *Time Period*: `1`
  ** *Time Unit*: *Minute*
  ** *Method & Resource conditions*: *Apply configurations to all API methods & resources*
. Select *Expose Headers*.
. Click *Apply*.

The new policy is displayed at the bottom of the Policies home page.

Change the API instance label so it reflects the fact that we now have a policy on the proxy:

. Click *Settings*.
. Click the edit pencil next to *Label* and change the value to `Rate-limiting policy`. 

Test the new policy:

. Exercise the API proxy `http://hello-world-greeting-us-proxy.us-w1.cloudhub.io/greeting` from Advanced Rest Client multiple times, until you receive the response `429 Too Many Requests`.
 
=== Step 5: Set SLA Tiers

To add service-level agreement tiers, so that different customer groups have different rate limits applied:

. Open Hello-World in API Manager by clicking `v1`.
. Click *Add SLA tier*.
. Set the following values:
  ** *Name*: `Free`
  ** *Approval*: *Automatic*
  ** *# of Reqs*: `1`
  ** *Time Period*: `1`
  ** *Time Unit*: *Minute*
. Click *Add*.
. Create a second tier:
  ** *Name*: `Silver`
  ** *Approval*: *Manual*
  ** *# of Reqs*: `1`
  ** *Time Period*: `1`
  ** *Time Unit*: *Second*

Change the policy used by this API proxy to be rate limiting that is SLA based:

. Select *Policies*.
. Open *Rate limiting*.
. Select *Actions > Remove* and then confirm the removal.
. Create a new rate limiting policy based on SLA:
  .. Click Apply New Policy.
  .. Open *Rate limiting - SLA based*.
  .. Select the latest version.
  .. Click *Configure Policy*.
  .. Notice that you must supply a client ID expression and client secret expression in the API request headers.
  .. Select *Expose Headers*.
  .. Click *Apply*.
  .. Select *Settings*.
  .. Click the pencil next to *Label* and then change the value to `Rate limiting - SLA-based policy`.

Test the rate limiting by sending a single GET request in Advanced Rest Client or similar. You should receive a `401 Unauthorized` error because you didn't supply a client ID and client secret.

Customers must now request access to the API.

To test access request:

. Open Exchange for your organization.
+
link:https://anypoint.mulesoft.com/exchange["Take me there^", role="button-primary"]
. Click *Hello-World* (Rest API).
. Click the green GET button.
. Click *Request access*.

=== Step 6: Set API monitoring alerts

=== Step 7: Configure the application and infrastructure for deployment

=== Step 8: Deploy an application version

=== Step 9: Sanity test the deployment

=== Step 10: Update portal with implementation URL

3.3 Manage application

* Approve, reject, revoke access to APIs by consumers
* Scale capacity
* Test performance and failure scenarios with third-party tools
* Promote app and policies

== Developer Deep Dive

3.2 Secure non-Mule APIs with an API proxy

* Import proxy application version to API Manager
* Apply policies
* Set SLA tiers
* Set API monitoring alerts
* Set a proxy consumer endpoint
* Deploy the API proxy
* Sanity test the deployment
