= Develop the API Interface and Implementation
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Now that you have created an API specification, you can build and test the API you plan to deploy.
We'll build the business logic into an implementation XML file, and then import the API specification
to take advantage of the automated scaffolding that Studio and APIkit provide, in order to complete the API interface.

Finally, we'll add unit tests and test the API, all from Studio.

== Build the API

You've created an API specification--now it's time to create the API (or connect to an existing one using the information in the specification).
In MuleSoft, you package the business logic (implementation) and the interface in an application that is deployed to a Mule runtime engine instance.

The steps in this section assume you have launched Studio before each Step.

=== Step 1: Add Your Anypoint Platform Credentials to Studio

Add your Anypoint Platform credentials in Studio once, and they'll be available for all the projects you create.

. In Studio, open the *Preferences* dialog.
. Select *Anypoint Studio > Authentication*.
. Enter your Anypoint Platform username and password.
. Click *Sign in*.
. Click *Apply and Close*.

These credentials are available for the duration indicated when you entered them, seven days by default.

=== Step 2: Create a New Project with an Imported API Specification

To deploy an API to the Mule runtime engine in the target of your choice, 
build the interface and implementation in a Mule app using Studio. In this step,
we'll create the project.

. In Studio, select *File > New > Mule Project*.
. In the dialog box, provide the following values:
  ** *Project Name*: Hello-World
  ** *Runtime*: If there is a choice, select the latest version of Mule. This is the Mule runtime engine that is hosted within Studio for testing.
  ** Select the *From Design Center or local files* tab.
    . Click the button to the right of the *Location* field.
    . Select *Design Center*.
    . If the correct username for your Anypoint Platform org appears, you'll see a list of API specifications.
    . Choose *Hello World*.
    . Click *OK*.
    . Make sure the checkbox *Scaffold flows from these API specifications* is selected.
    . To verify the import, check Package Explorer for `hello-world/src/main/resources/api/hello-world.raml`.

Studio opens the *hello-world.xml* XML file,
which contains some of the basic elements you'll need for the API interface. Next, we'll configure these elements,
and later on we'll create the business logic in a separate XML file for the implementation. 

=== Step 3: Configure the RESTful API Interface

Using the scaffolding provided by Studio, complete the RESTful API interface:

. In Studio, right-click `hello-world/src/main/mule/hello-world.xml` and select *Refactor > Rename*.
. Rename the file: `interface.xml`.
. Configure the main listener:
  .. In the canvas, click the *hello-world-main* Listener to display the General configuration tab.
  .. Click the green plus sign to create a global configuration for HTTP listeners in this project.
  .. Verify that the host is `0.0.0.0` and the port is `8081`.
  .. Click *Test Connection*, and then click *OK* when the connection is successful.
  .. If you click *Global Elements* at the bottom of the canvas, you'll see this configuration is a global configuration.
. Click *Configuration XML* at the bottom of the canvas to see the XML that has been created.

Once we have an implementation set up, we'll return to `interface.xml`.

=== Step 4: Create the RESTful API Implementation

Find and assemble the elements needed to define the business logic of your API:

. In Studio, select *File > New > Mule Configuration File*.
. Select the project `hello-world`, and then name the file `implementation.xml`.
. Click *Finish*.
. Add an HTTP connector endpoint to receive requests:
  .. In the *Mule Palette*, select *HTTP*, the HTTP module.
  .. Drag *Listener* from the *Mule Palette* to the canvas. This action creates a flow containing the listener.
. Specify the global properties that the Listener needs:
  .. Double-click HTTP Listener.
  .. In the General tab of the Listener properties, notice that the global configuration that you created in Step 3 is displayed. If it is not, select it.
  .. Set *Path* to */greeting*, the resource we specified in xref:api-led-design.adoc[Design an API specification].
  .. Save your changes.
. Specify logic to display the data from Hello World:
  .. Return to the *Mule Palette* and select *Favorites* or *Core* to display the *Set Payload* transformer.
  .. Find and drag *Set Payload* into the flow and leave it selected.
  .. In the *General* tab, set *Value* under *Settings* to *Today the greeting is Hello.*
. Save your work, and then review the XML generated by your work in *Configuration XML*, and then return to *Message Flow*.

You have created a simple Mule app with an interface and an implementation.
Studio provides a Mule runtime engine wher you can deploy and run your app for testing.

=== Step 5. Test the API

Run the Studio project that contains your API in the Mule runtime engine and then test with a third-party client:

. Right-click anywhere on the canvas and select *Run project hello world*.
. The console opens and displays status messages as the app is deployed to the Mule runtime engine (Mule) contained within Studio.
+
When the following message is displayed, the app containing your API has been deployed to Mule.
. To exercise the app, open a REST client (Postman) and issue a GET request:
  `\http://localhost:8081/greeting`.
. Your REST client should return a `200 OK` message and the body `Today the greeting is Hello.`.
. Right-click in the canvas and select *Stop project hello-word*.

=== Step 6. Publish the API to Exchange

Publish the API to Exchange so it can serve as a template or example for others.

. From the Package Explorer in Studio, right-click the `hello-world` project.
. Select *Anypoint Platform > Publish to Exchange*.
. Select the username and business group who will serve as the publishers of record. After you select values that have permission to publish to Exchange, the *Finish* button is enabled.
. The *Version* number is incremented for you, based on the previous version published. You can change the number.
. Click *Finish*.
. Click *Yes* when asked to proceed.

After the project deploys and is uploaded to Exchange, you are provided with a direct link to the project.

. Click the link to view the project in Exchange. 
. You can add documentation, descriptions, and tags that aid search.
. Review the listed dependencies. In this case Validation Module, Sockets Connector, and HTTP Connector are listed as dependencies.
. When you are satisfied with the publication, return to Studio and click *OK* to close the open dialog windows.

== What's Next

Add validation, event logging to support debugging, error handling, and a unit test to your API.

== Developer Deep Dives

APIs can do much more than this simple HTTP request in the API you just created and tested.

You can:

* Transform data with DataWeave: xref:mule-runtime::dataweave-quickstart.adoc[Quickstart], xref:mule-runtime::mule-app-tutorial.adoc[Tutorial].
* Structure Mule applications using xref:mule-runtime::about-flows.adoc[flows, subflows, and asynchronous queues].
* Define and manage application metadata (schemas): xref:studio::metadata-editor-concept.adoc[Metadata Editor].
* Implement key-performance indicators using xref:api-manager::analytics-landing-page.adoc[API Manager analytics].
* Conditionally route events: xref:mule-runtime::choice-router-concept.adoc[choice router], xref:mule-runtime::scatter-gather-concept.adoc[scatter gather router].
