= Step 1. Prerequisites for Building an API
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:experimental:

Before you begin your API-led journey, verify that you have the basic tools and access needed.

* Username and password for your Anypoint Platform organization. If you don't have Anypoint Platform yet, create a Trial organization on Anypoint Platform.
+
link:https://anypoint.mulesoft.com/login/#/signup["Create a Trial organization^", role="button-primary"]
* Download Anypoint Studio version 7.4.1 or later. Anypoint Studio is an Eclipse-based IDE with rich functionality for building and deploying to Anypoint Platform. 
+
link:https://www.mulesoft.com/lp/dl/studio["Download Anypoint Studio^", role="button-primary"]
* To test REST requests, obtain a client such as Advanced REST Client or Postman if you don't already have one.
+
link:https://install.advancedrestclient.com/install["Install Advanced REST Client^", role=button-primary"]

== Helpful Hints

* Use two browser windows: one to read instructions and one to perform the tasks.
* Set your REST client to have a long timeout. When we step through the processes one at a time, you don't want your REST request to time out.