= Step 1. Prerequisites for Building an API
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:experimental:

Before you begin your API-led journey, verify that you have the required tools and access:

* Username and password for your Anypoint Platform organization. If you don't have Anypoint Platform yet, create a Trial organization on Anypoint Platform.
+
link:https://anypoint.mulesoft.com/login/#/signup["Create a Trial organization^", role="button-primary"]
* Download Anypoint Studio 7.4.1 or later. Anypoint Studio is an Eclipse-based IDE with rich functionality for building and deploying apps to Anypoint Platform. 
+
link:https://www.mulesoft.com/lp/dl/studio["Download Anypoint Studio^", role="button-primary"]
* To test REST requests, obtain a client such as Advanced REST Client or Postman if you don't already have one. This tutorial uses Advanced REST Client.
+
link:https://github.com/advanced-rest-client/arc-electron/releases["Install Advanced REST Client^", role=button-primary"]
+
Depending on your platform, you might need to install a different client, or https://github.com/advanced-rest-client/arc-electron/releases[install Advanced REST Client from GitHub].

== Helpful Hints

* Use two browser windows: One to read instructions and one to perform the tasks.
* Set Advanced REST Client to have a long timeout. When you step through the processes during debugging, you don't want the REST request to time out.