= Browser Support for Anypoint Platform
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: api-community-manager::browser-support.adoc

Use Anypoint Platform with the latest version of any supported browser:

* Microsoft Edge with Chromium
* Microsoft Edge without Chromium (supported through December 31, 2020)
* Google Chrome
* Mozilla Firefox
* Safari

The Anypoint Platform browser support follows the Salesforce Lightning Experience policy.

== Exceptions to Browser Support Policy

API Community Manager and Partner Manager 2.0 each modify the browser support policy:

* xref:api-community-manager::data-sheets.adoc
* xref:release-notes:partner-manager:anypoint-partner-manager-2.0-release-notes#browser-compatibility.adoc

== Unsupported Browsers

Internet Explorer versions 11 and earlier are not supported by MuleSoft.
If you use the browser with Anypoint Platform, you might experience issues.

== See Also

https://help.salesforce.com/articleView?id=getstart_browsers_sfx.htm&type=5[Supported Browsers for Lightning Experience^]
