= Browser Support for Anypoint Platform
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: api-community-manager::browser-support.adoc

Use Anypoint Platform with the latest version of any supported browser:

[tabs]
====
Microsoft Edge::
* with Chromium
* without Chromium (supported through December 31, 2020)
Google Chrome::
* stable
* dev
Mozilla Firefox::
* latest release
Safari::
* macOS Ventura
====

Browser support for Anypoint Platform follows the Salesforce Lightning Experience policy.

== Exceptions to Browser Support Policy

Partner Manager 2.0 modifies the browser support policy:

* xref:release-notes::partner-manager/anypoint-partner-manager-2.0-release-notes.adoc#browser-compatibility[Partner Manager 2.0]

== Unsupported Browsers

Internet Explorer versions 11 and earlier are not supported.
If you use the browser with Anypoint Platform, you might experience issues.

== See Also

https://help.salesforce.com/articleView?id=getstart_browsers_sfx.htm&type=5[Supported Browsers for Lightning Experience^]
