= Upgrading Java for Custom Connectors (Customers)

NOTE: This guide applies to MuleSoft customers only. If you are a MuleSoft partner, see xref:partner-connector-upgrade.adoc[].

Upgrade, test, and release your custom connectors for Java 17 to ensure compatibility within the MuleSoft ecosystem. 

include::partial$partner-and-customer-guide.adoc[tags=before-you-begin]

To decouple the minimum Mule version when running tests, add the `-Dmunit.jvm` parameter to use Java 17 as described in <<test-your-custom-connector-with-munit>>.

include::partial$partner-and-customer-guide.adoc[tags=mule-sdk-connectors]

include::partial$partner-and-customer-guide.adoc[tags=rest-connect-connectors]

[[test-your-custom-connector-with-munit]]
== Test Your Custom Connector with MUnit

Run your MUnit tests to test compatibility of your connector against Java 17. Ensure your local JDK version is 17. 

. Open the pom.xml file of your Mule app.
. Replace the `mule-maven-plugin` version with the `${mule.maven.plugin.version}` parameter.
. If you haven’t already, add the `munit-maven-plugin`. Replace the version with the `${munit.version}` parameter and replace `runtimeVersion` with the `${app.runtime}` parameter.
+
[source,xml,linenums]
----
	<plugin>
		<groupId>com.mulesoft.munit.tools</groupId>
		<artifactId>munit-maven-plugin</artifactId>
		<version>${munit.version}</version>
		<executions>
			<execution>
				<id>test</id>
				<phase>test</phase>
				<goals>
					<goal>test</goal>
					<goal>coverage-report</goal>
				</goals>
			</execution>
		</executions>
		<configuration>
			<coverage>
				<runCoverage>true</runCoverage>
				<formats>
					<format>html</format>
				</formats>
			</coverage>
			<runtimeVersion>${app.runtime}</runtimeVersion>
			<dynamicPorts>
				<dynamicPort>http.port</dynamicPort>
			</dynamicPorts>
		</configuration>
	</plugin>
----
+
NOTE: MUnit 3.1 is compatible only with Mule runtime 4.3.0 and later. If your connector is compatible with Mule runtime 4.2.0 and earlier, you must create a legacy profile that overrides the MUnit version.
. If you have MUnit dependencies, such as `munit-runner` and `munit-tools`, replace the version for each dependency with the `${munit-version}` parameter.
. Replace the version for each connector dependency with the Java 17 compatible version of the connector.
. Open a terminal window in the root of your Mule project and run the following command:
+
[source,bash]
----
mvn -f pom.xml -s ~/.m2/settings.xml -Dapp.runtime=4.6.0 -Dmunit.version=3.1.0 -Dmule.maven.plugin.version=4.1.0 -fae test
----

You can now see if your connector is compatible with Java 17. For more information about running MUnit tests, refer to xref:munit::index.adoc[MUnit]. 

include::partial$partner-and-customer-guide.adoc[tags=communicate-support-level]

== See Also

* xref:java-support.adoc[]
