= Anypoint Platform Deployment Options
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Platform is an advanced enterprise platform for designing, developing, and managing APIs, 
as well as connecting APIs with applications, data, and devices. Anypoint Platform functionality can be classified into two main categories:

* Control plane functionality
+ 
Anypoint Platform control plane functionality includes the design, engagement, and management capabilities of Anypoint Platform, such as Design Center, Management Center, and Exchange.
* Runtime plane functionality 
+ 
Anypoint Platform runtime plane functionality includes the runtime engine (Mule) and runtime services, such as Anypoint Connectors, Anypoint Object Store, and messaging, that allow you to scale the power of Mule and Anypoint Platform and where applications are deployed.

== Plane Functionality Location and Management
The needs of your organization determine where Anypoint Platform control plane and runtime plane functionality are deployed: on-premises, in the cloud, or in a hybrid environment, and also determine who manages and maintains the control and runtime plane functionality. Anypoint Platform control and runtime plane location and management options include:

* CloudHub
+
MuleSoft hosts and manages public cloud infrastructure for both control and runtime planes. 
* Hybrid
+
MuleSoft hosts and manages public cloud infrastructure for the control plane, with the runtime plane deployed in a hybrid configuration: both Anypoint Runtime Fabric and on CloudHub.
* On-premises
+
MuleSoft hosts and manages public cloud infrastructure for the control plane, with the runtime plane deployed to customer-owned and operated datacenter infrastructure. This can include traditional “bare-metal”, virtualized, on-prem, private cloud (PaaS), and public cloud environments. 
* Anypoint Platform Private Cloud Edition (Anypoint Platform PCE)
+
Control plane and runtime plane are both hosted on the customer’s premises. This does not include Mule ESB on-prem, either with MMC or without management.

The following table summarizes Anypoint Platform plane functionality location and management options:

[%header,cols="5*a"]
|===
| Plane | CloudHub | Hybrid | On-Premises | Anypoint Platform PCE
| Control plane | Located in the US, EU, and US-based FedRAMP certified regions | Located in the US and EU regions | Located in the US and EU regions | Located on-premises
| Control plane managed and maintained by | MuleSoft | MuleSoft | MuleSoft | You (either on-premises or in a cloud environment)
| Runtime plane | Located in 13 regions globally 
a| 

* Located in 13 regions globally 
* Located in your datacenters (using Anypoint Runtime Fabric or virtual machines) | Located in your datacenters (using Anypoint Runtime Fabric or virtual machines) | Located in your datacenters
| Runtime plane managed and maintained by | MuleSoft 
a| 

* MuleSoft manages runtime planes in global regions. 
* You manage runtimes in your datacenters (either on-premises or in a cloud environment. | You | You
|===

== Anypoint Platform Deployment Options
Your Anypoint Platform deployment option is based on both control and runtime plane location and management as well as data hosting requirements, as shown in the following list:

* US cloud
+
The complete Anypoint Platform. All data is hosted within the US.
* EU cloud
+
Includes all US cloud components, but differs from the US cloud in that all data is hosted within the EU. Refer to xref:eu-control-plane::index.adoc[About the EU Control Plane] for additional information.
* MuleSoft Government Cloud
+
FedRAMP moderate authorized version of US cloud. Refer to xref:gov-cloud::index.adoc[About Government Cloud] for additional information.
* Anypoint Platform PCE
+
A single-tenant version of US cloud managed by your IT team. Anypoint Platform PCE supports on-premises and cloud installation and is specifically designed for customers with strict regulatory or compliance requirements that limit the use of cloud solutions. Refer to xref:private-cloud::index.adoc[About Anypoint Platform Private Cloud Edition] for additional information.

== Deployment Components

Each Anypoint Platform deployment supports a different set of individual Anypoint Platform components, but the actual components in your deployment is dependent on your Anypoint Platform subscription. Refer to https://www.mulesoft.com/anypoint-pricing for detailed Anypoint Platform subscription information.

=== Control Plane Components
The following table summarizes Anypoint Platform control plane components and their overall availability across deployment options: 

[%header,cols="4*a"]
|===
| Anypoint Platform Component | US/EU Cloud | MuleSoft Government Cloud | Anypoint Platform PCE
| API Designer | Y  | Y | Y
| Anypoint Studio | Y  | Y | Y
| Flow Designer | Y  | N | N
| Anypoint Exchange | Y  | Y | Y
| Anypoint API Community Manager* | Y  | N | N
| Anypoint Partner Manager | Y  | N | N
| Access management | Y  | Y | Y
| Analytics | Y  | N | N
| Anypoint API Manager | Y  | Y | Y
| Anypoint Runtime Manager | Y  | Y | Y (excluding Insights)
| Anypoint Monitoring | Y  | N | N
| Secrets manager | Y  | N | N
| Anypoint Visualizer | Y  | N | N
| Anypoint Security edge policies | Y | N | N
| Anypoint Security tokenization | Y | N | N
|===

* xref:api-community-manager/index.adoc[Anypoint API Community Manager] (API Community Manager) is designed to leverage the capabilities and functionality of the Salesforce platform.

=== Runtime Plane Components
The individual Anypoint Platform runtime plane components in your deployment is dependent on which of the following runtime plane options applies to your environment:

* CloudHub
+
MuleSoft hosts and manages the runtime plane.
* Anypoint Runtime Fabric (Runtime Fabric)
+
You deploy Mule runtimes on your own infrastructure, whether it’s in a private IaaS (Microsoft Azure or AWS) or in an on-premises data center. You can still reap the benefits of CloudHub, such as horizontal scalability and zero downtime redeployments, while keeping your runtimes on-premises.
* On-premises Mule runtime engine instances (Mule instances)
+
You host and manage your own infrastructure.
* Hybrid
+
Hybrid environments include both CloudHub and on-premises Mule functionality.

The following table summarizes Anypoint Platform runtime plane components and their overall availability across deployment options:

[%header,cols="4*a"]
|===
Runtime Plane | US/EU Cloud | MuleSoft Government Cloud | Anypoint Platform PCE
| CloudHub | Y | Y | N
| Runtime Fabric | Y | N | N
| On-premises Mule instances | Y | N | Y
|===

The following table summarizes individual Anypoint Platform runtime plane components and their availability across runtime plane options:

[%header,cols="4*a"]
|===
| Anypoint Platform Component | CloudHub | Runtime Fabric | On-premises Mule instances 
| Mule runtime engine | Y | Y | Y
| Anypoint MQ | Y | N | N
| Anypoint Object Store | Y | N | Y
| Connectors | Y | Y | Y
|===

== How to Identify Your Anypoint Platform Control and Runtime Planes
You can use your Anypoint Platform product URL to help determine what your environment contains: 

* To identify the control plane deployment option in use:
** Anypoint Platform PCE URLs reflect an internal domain set up by your organization: for example, `pce.yourname.net`.
** URLs for deployments other than Anypoint Platform PCE contain information to identify the type of deployment: 
*** https://eu1.anypoint.mulesoft.com (for EU cloud) 
*** https://gov.anypoint.mulesoft.com (for MuleSoft Government Cloud) 
*** https://anypoint.mulesoft.com (for US Cloud) 
* To identify the runtime plane deployment option in use for an application, check the deployment option listed for that application in Runtime Manager:
** For an application deployed to CloudHub, the deployment target that is listed in Runtime Manager is set to `CloudHub`.
** For an application deployed to Runtime Fabric, the deployment target that is listed in Runtime Manager is the 
name of the Runtime Fabric.
** For an application deployed to an on-premises, standalone Mule instance, the deployment target listed in 
Runtime Manager is a registered server, server group, or cluster.
