= Anypoint Platform Deployment Options
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Platform provides multiple deployment options, each of which differs based on data hosting requirements, the location and management of Anypoint Platform, and the individual Anypoint Platform components included: 

* US cloud (CloudHub)
+
The complete Anypoint Platform. All data is hosted within the US.
* EU cloud
+
Contains most Anypoint Platform components. All data is hosted within the EU. Refer to xref:eu-control-plane::index.adoc[About the EU Control Plane] for additional information.
* MuleSoft Government Cloud
+
FedRAMP moderate impact level authorized version of US cloud. Refer to xref:gov-cloud::index.adoc[About Government Cloud] for additional information.
* Anypoint Platform PCE
+
A single-tenant version of US cloud managed by your IT team. Anypoint Platform PCE supports on-premises and cloud installation and is specifically designed for customers with strict regulatory or compliance requirements that limit the use of cloud solutions. Refer to xref:private-cloud::index.adoc[About Anypoint Platform Private Cloud Edition] for additional information.  

== Anypoint Platform Location and Management
Your organization's needs determine where Anypoint Platform functionality is deployed and who manages it. Anypoint Platform functionality can be classified into two main categories:

* Control plane
+ 
Anypoint Platform control plane functionality includes the design, engagement, and management capabilities of Anypoint Platform, such as Anypoint Design Center, Anypoint Management Center, and Anypoint Exchange.
* Runtime plane
+
Anypoint Platform runtime plane functionality includes the runtime engine (Mule) and runtime services, such as Anypoint Connectors, Anypoint Object Store, and Anypoint MQ that enable you to scale the power of Mule and Anypoint Platform, and is where applications are deployed.

Anypoint Platform control plane and runtime plane functionality can be deployed on-premises, in the cloud, or in a hybrid environment in the following configurations:

* CloudHub
+
MuleSoft hosts and manages public cloud infrastructure for both control and runtime planes. 
* Hybrid
+
MuleSoft hosts and manages public cloud infrastructure for the control plane. The runtime plane is deployed in a hybrid configuration: a combination of Anypoint Runtime Fabric, virtual machines, and CloudHub.
* On-premises
+
MuleSoft hosts and manages public cloud infrastructure for the control plane, with the runtime plane deployed to customer-owned and operated datacenter infrastructure. This can include traditional bare-metal, virtualized, private cloud (PaaS), and public cloud environments. 
* Anypoint Platform Private Cloud Edition (Anypoint Platform PCE)
+
The control and runtime planes are both hosted on the customer’s premises. This does not include Mule ESB on-premises, either with or without Mule Management Console (MMC).

The following table compares Anypoint Platform configurations:

[%header,cols="5*a"]
|===
| Plane | CloudHub | Hybrid | On-Premises | Anypoint Platform PCE
| Control plane location | US, EU, and US-based FedRAMP certified regions | US and EU regions | US and EU regions | On-premises
| Control plane managed and maintained by | MuleSoft | MuleSoft | MuleSoft | You (either on-premises or in a cloud environment)
| Runtime plane location | US: 13 regions globally, EU: 2 regions
a| 

* US: 13 regions globally, EU: 2 regions 
* Your datacenters (using Anypoint Runtime Fabric or virtual machines) | Your datacenters (using Anypoint Runtime Fabric or virtual machines) | Your datacenters
| Runtime plane managed and maintained by | MuleSoft 
a| 

* MuleSoft manages runtime planes in global regions. 
* You manage runtimes in your datacenters (either on-premises or in a cloud environment. | You | You
|===

== Anypoint Platform Components

Each Anypoint Platform deployment supports a different set of individual Anypoint Platform components, but the specific components in your deployment depends on your Anypoint Platform subscription. Refer to https://www.mulesoft.com/anypoint-pricing for detailed Anypoint Platform subscription information.

=== Control Plane Components
The following table summarizes Anypoint Platform control plane component availability across deployment options: 

[%header,cols="5*a"]
|===
| Anypoint Platform Component | US Cloud | EU Cloud | MuleSoft Government Cloud | Anypoint Platform PCE
| API Designer | Y | Y | Y | Y
| Anypoint Studio | Y | Y | Y | Y
| Flow Designer | Y | Y | N | N
| Anypoint Exchange | Y | Y | Y | Y
| Anypoint API Community Manager* | Y | Y | N | N
| Anypoint Partner Manager | Y | N | N | N
| Access management | Y | Y | Y | Y
| Analytics | Y | Y | N | N
| Anypoint API Manager | Y | Y | Y | Y
| Anypoint Runtime Manager | Y | Y | Y | Y (excluding Insight)
| Anypoint Monitoring | Y | Y | N | N
| Secrets manager | Y | Y | N | N
| Anypoint Visualizer | Y | Y | N | N
| Anypoint Security edge policies | Y | Y | N | N
| Anypoint Security tokenization | Y | Y | N | N
|===

* Anypoint API Community Manager (API Community Manager) is designed to leverage the capabilities and functionality of the Salesforce platform.

=== Runtime Plane Components
Anypoint Platform runtime plane component availability is based on your runtime plane functionality:

* CloudHub
+
MuleSoft hosts the runtime plane.
* Anypoint Runtime Fabric (Runtime Fabric)
+
Your runtime plane is hosted on your infrastructure, whether it’s in a private IaaS (Microsoft Azure or AWS) or on traditional bare-metal servers.
* On-premises Mule runtime engine instances (Mule instances)
+
Your runtime plane is hosted on your infrastructure, including, virtualized, private cloud (PaaS), public cloud, and traditional bare-metal environments.
* Hybrid
+
Hybrid environments include both CloudHub and on-premises Mule functionality.

The following table summarizes Anypoint Platform runtime plane component availability across runtime plane functionality:

[%header,cols="4*a"]
|===
| Anypoint Platform Component | CloudHub | Runtime Fabric | On-premises Mule instances 
| Mule runtime engine | Y | Y | Y
| Anypoint MQ | Y | N | N
| Anypoint Object Store | Y | N | Y
| Connectors | Y | Y | Y
|===

== How to Identify Your Anypoint Platform Control and Runtime Planes
You can use your Anypoint Platform product URL to help determine your deployment option: 

* To identify the control plane deployment option in use:
** Anypoint Platform PCE URLs reflect an internal domain set up by your organization: for example, `pce.yourname.net`.
** URLs for deployments other than Anypoint Platform PCE contain information to identify the type of deployment: 
*** https://eu1.anypoint.mulesoft.com (for EU cloud) 
*** https://gov.anypoint.mulesoft.com (for MuleSoft Government Cloud) 
*** https://anypoint.mulesoft.com (for US Cloud) 
* To identify the runtime plane deployment option in use for an application, check the deployment option listed for that application in Runtime Manager:
** For an application deployed to CloudHub, the deployment target that is listed in Runtime Manager is set to `CloudHub`.
** For an application deployed to Runtime Fabric, the deployment target that is listed in Runtime Manager is the 
name of the Runtime Fabric.
** For an application deployed to an on-premises, standalone Mule instance, the deployment target listed in 
Runtime Manager is a registered server, server group, or cluster.
