= Anypoint Platform Deployment Options
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Platform is an advanced enterprise platform for designing, developing, and managing APIs, 
as well as for connecting APIs with applications, data, and devices. It enables you to deploy applications 
anywhere on-premises, in the cloud, or in a hybrid environment to reliably address both small-scale and 
mission-critical use cases.

Anypoint Platform functionality can be classified into two main categories:

* Control plane
+ 
The Anypoint Platform control plane provides design, engagement, and management capabilities.
* Runtime plane. 
+ 
The Anypoint Platform runtime plane is where applications are deployed, and also where Mule runtime engine (Mule)
and other application-related services, such as Anypoint Connectors, Anypoint Object Store, and messaging, run. 

The following table lists Anypoint Platform control and runtime plane components: 

[%header,cols="2*a"]
|===
| Anypoint Platform Control Plane Components | Anypoint Platform Runtime Plane Components
a|
* API Designer 
* Anypoint Studio 
* Flow Designer 
* Anypoint Exchange 
* Anypoint API Community Manager 
* Anypoint Partner Manager
* Access management
* Analytics
* Anypoint API Manager
* Anypoint Runtime Manager 
* Anypoint Monitoring
* Secrets manager
* Anypoint Visualizer 
a|
* Mule runtime engine
* Anypoint Security edge policies
* Anypoint Security tokenization
* Anypoint MQ
* Anypoint Object Store
|===

== Control and Runtime Plane Locations and Management
With Anypoint Platform, you choose where to host your control and runtime planes and whether you want to 
manage them, which then determines the Anypoint Platform deployment option that is right for you. 
The following tables summarize the options for control and runtime plane locations and management: 

[%header,cols="5*a"]
|===
| Plane | CloudHub | Hybrid | On-Premises | On-Premises Using Private Cloud Edition
| Control plane | Located in the US, EU, and US-based FedRAMP certified regions. | Located in the US and EU regions. | Located in the US and EU regions. | Located on-premises.
| Control plane managed by | MuleSoft | MuleSoft | MuleSoft | You
| Runtime plane | Located in 13 regions globally. 
a| 

* Located in 13 regions globally. 
* Located in your environment (using Anypoint Runtime Fabric or virtual machines). | Located in your environment (using Anypoint Runtime Fabric or virtual machines). | Located in your environment (on virtual machines).
| Runtime plane managed by | MuleSoft 
a| 

* MuleSoft manages runtime planes in global regions. 
* You manage runtimes in your environment. | You | You
|===

== Deployments and Components
Anypoint Platform control plane and runtime components, and their availability across deployment options, are listed in the following tables. Deployment options include:

* US cloud
The complete Anypoint Platform. All data is hosted within the US.
* EU cloud
Includes all US cloud components, but differs from the US cloud in that all data is hosted within the EU. Refer to xref:eu-control-plane::index.adoc[About the EU Control Plane] for additional information.
* MuleSoft Government Cloud
FedRAMP moderate authorized version of US cloud. Refer to xref:gov-cloud::index.adoc[About Government Cloud] for additional information.
* Anypoint Platform Private Cloud Edition (Anypoint Platform PCE)
A single-tenant version of US cloud managed by your IT team. Anypoint Platform PCE supports on-premises and cloud installation and is specifically designed for customers with strict regulatory or compliance requirements that limit the use of cloud solutions. Refer to xref:private-cloud::index.adoc[About Anypoint Platform Private Cloud Edition] for additional information.

Refer to https://www.mulesoft.com/anypoint-pricing for Anypoint Platform component availability based on your subscription.

=== Control Plane Components and Availability Across Deployment Options
[%header,cols="5*a"]
|===
| Anypoint Platform Component | US Cloud | EU Cloud | MuleSoft Government Cloud | Anypoint Platform PCE
| API Designer | Y | Y | Y | Y
| Anypoint Studio | Y | Y | Y | Y
| Flow Designer | Y | Y | N | N
| Anypoint Exchange | Y | Y | Y | Y
| Anypoint API Community Manager* | Y | Y | N | N
| Anypoint Partner Manager | Y | Y | N | N
| Access management | Y | Y | Y | Y
| Analytics | Y | Y | N | N
| Anypoint API Manager | Y | Y | Y | Y
| Anypoint Runtime Manager | Y | Y | Y | Y (excluding Insights)
| Anypoint Monitoring | Y | Y | N | N
| Secrets manager | Y | Y | N | N
| Anypoint Visualizer | Y | Y | N | N
|===

*Anypoint API Community Manager (API Community Manager) is powered by the Salesforce platform.

=== Runtime Plane Options and Deployments
For the Anypoint Platform runtime plane, you have three options: CloudHub, Anypoint Runtime Fabric (Runtime Fabric), 
or on-premises Mule runtime engine instances (Mule instances). Hybrid environments include both CloudHub and on-premises Mule functionality.

* CloudHub
+
With CloudHub, MuleSoft hosts and manages the infrastructure. Enterprise-grade capabilities, such as 99.99% uptime, one-click scalability, and automatic updates, are provided as a service.
* Runtime Fabric
+
Use Anypoint Runtime Fabric (Runtime Fabric) if you have requirements to deploy Mule runtimes on your own infrastructure, whether it’s in a private IaaS (Microsoft Azure or AWS) or in an on-premises data center. You can still reap the benefits of CloudHub, such as horizontal scalability and zero downtime redeployments, while keeping your runtimes on-premises.
* On-premises Mule runtime engine instances
+
Use standalone Mule instances when you want to host and manage your own infrastructure.

==== Runtime Plane Availability Across Deployment Options
[%header,cols="5*a"]
|===
Runtime Plane | US Cloud | EU Cloud | MuleSoft Government Cloud | Private Cloud Edition
| CloudHub | Y | Y | Y | N
| Runtime Fabric | Y | Y | N | N
| On-premises Mule instances | Y | Y | N | Y
|===

==== Runtime Plane Component Availability Across Runtime Plane Options
[%header,cols="4*a"]
|===
| Anypoint Platform Component | CloudHub | Runtime Fabric | On-premises Mule instances 
| Mule runtime engine | Y | Y | Y (excluding DataWeave)
| Anypoint Security edge policies  | N | Y | N 
| Anypoint Security tokenization | N | Y | N
| Anypoint MQ | Y | N | N
| Anypoint Object Store | Y | N | N
|===

== How to Identify Your Anypoint Platform Control and Runtime Planes
You can use your Anypoint Platform product URL to help determine what your environment contains: 

* To identify the control plane deployment option in use:
** Anypoint Platform PCE URLs reflect an internal domain set up by your organization: for example, `pce.yourname.net`.
** URLs for deployments other than Anypoint Platform PCE contain information to identify the type of deployment: 
*** https://eu1.anypoint.mulesoft.com (for EU cloud) 
*** https://gov.anypoint.mulesoft.com (for MuleSoft Government Cloud) 
*** https://anypoint.mulesoft.com (for US Cloud) 
* To identify the runtime plane deployment option in use for an application, check the deployment option listed for that application in Runtime Manager:
** For an application deployed to CloudHub, the deployment target that is listed in Runtime Manager is set to `CloudHub`.
** For an application deployed to Runtime Fabric, the deployment target that is listed in Runtime Manager is the 
name of the Runtime Fabric.
** For an application deployed to an on-premises, standalone Mule instance, the deployment target listed in 
Runtime Manager is a registered server, server group, or cluster.
