= Trying Out Your Model Proxy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:page-aliases: gateway::llm-proxy-try-out.adoc, gateway::flex-gateway-llm-proxy-try-out.adoc

Model Proxy provides the try out functionality to test mock LLM prompts without creating API requests. Use the try out feature to test:

* What response message your Model Proxy returns.
* What response headers are returned.
* What model services the response.
* Why a request is sent to a specific route.

NOTE: The Try Out feature only supports Model Proxies configured with OpenAI input format. For Model Proxies configured with Gemini or Anthropic native formats, use the request examples in xref:model-proxy-request.adoc[] to test your proxy.

== Try Out Your Model Proxy

. From API Manager in Anypoint Platform, click *Model Proxies*.
. Click the name of the Model Proxy you want to try out.
. Click *Try out*.
. Configure any authentication or other headers your request requires.
. Enter your test prompt.
. Click *Run test*.
. View the *LLM response*, *Response headers*, and *Test result* for details about your test request.
