= MuleSoft Automation Credits 3.0

MuleSoft Automation Credits 3.0 is available in Digital Wallet. Use Automation Credits 3.0 with MuleSoft for Flow: Integration, Anypoint IDP, MuleSoft for Flow: IDP, or a combination of these products, as more fully described in the applicable https://www.salesforce.com/company/legal/mulesoft-subscription-plan/[Subscription Plan] or Features and Entitlement Document.

If you have MuleSoft Automation Credits 3.0, usage visibility, monthly statements, and overage billing are all centralized within the Salesforce Digital Wallet. If you have an Anypoint Platform organization, view your usage and entitlement details within Anypoint Usage Reports for cross-platform transparency.

*Note:* MuleSoft Composer and Robotic Process Automation (RPA) are moving to the end of sale. As of February 18, 2026, Flow Orchestration is free and does not consume Automation Credits in 3.0.

[%header%autowidth.spread]
|===
| Usage Type | Description | Conversion rate (Credits per unit)

| *MuleSoft for Flow: Integration*
| Integration capabilities within Salesforce Flow; consumes Automation Credits for integration tasks.
| 2 credits per successful task

| *IDP Document Pages (Anypoint Platform)*
| IDP on Anypoint Platform; consumes credits for IDP document pages.
| 30 credits per page

| *MuleSoft for Flow: IDP*
| IDP capabilities within Salesforce Flow; consumes Automation Credits for document processing in Flow.
| 30 credits per page
|===

Rates and usage types for Automation Credits 3.0 varies by subscription. Refer to the Usage Details table on your Order Form and the applicable Subscription Plan or Features and Entitlement Document.

To learn more about how Flex Credits are consumed, and when other types of credits are consumed with generative AI features, see https://help.salesforce.com/s/articleView?id=ai.generative_ai_usage.htm&type=5[Agentforce and Generative AI Usage and Billing^] in Salesforce Help.

== See Also

* xref:automation-credits-usage-and-rates.adoc[]
* xref:usage-reports.adoc[]
* https://help.salesforce.com/s/articleView?id=xcloud.wallet_enabled_products_rate_cards.htm&type=5[Digital Wallet–Enabled Consumption-Based Products^] (Salesforce Help)
