= Upgrading Java for Custom Connectors (Partners)

include::partial$partner-and-customer-guide.adoc[tags=partner-upgrade-note]

include::partial$partner-and-customer-guide.adoc[tags=connector-intro]

include::partial$partner-and-customer-guide.adoc[tags=before-you-begin]

include::partial$partner-and-customer-guide.adoc[tags=min-mule-version-mtf]

include::partial$partner-and-customer-guide.adoc[tags=mule-sdk-connectors]

include::partial$partner-and-customer-guide.adoc[tags=mule-sdk-connectors-review-mule-runtime]

include::partial$partner-and-customer-guide.adoc[tags=mule-sdk-connectors-add-missing-code]

[[upgrade-your-rest-sdk-connectors]]
== Upgrade Your Custom REST SDK Connectors

Use REST SDK version 0.8.0-RC4 to upgrade your custom REST SDK connectors to Java 17. 

REST SDK 0.8.0-RC4 generates Java 17-compatible connectors and maintains backward compatibility only with REST SDK 0.8.0-RC3 connectors built without Java customizations. Version 0.8.0-RC4 is not backward-compatible with REST SDK versions earlier than 0.8.0-RC3. 

When upgrading REST SDK connectors to Java 17:

* For REST SDK version 0.8.0-RC3 and earlier connectors with Java customizations, regenerate the connector with REST SDK 0.8.0-RC4 and port over any Java customizations. 
+
The resulting connector likely breaks compatibility with the previous version of the connector.

* For REST SDK 0.8.0-RC3 and earlier connectors without Java customizations, regenerate the connector with REST SDK 0.8.0-RC4. 
+
The resulting connector is backward-compatible with the previous version.

For more information about REST SDK, see https://beta.docs.mulesoft.com/beta-mule-sdk/mule-sdk/1.1/rest-sdk/rest-sdk-connectivity[REST SDK]. 

=== Upgrade an Existing Custom REST SDK Connector

If you previously generated a connector using REST SDK and you want to make that connector compatible with Java 17:

. Upgrade the REST SDK components and dependencies to version 0.8.0-RC4:
+
[source,xml,linenums]
----
<parent>
   <groupId>com.mulesoft.connectivity</groupId>
   <artifactId>rest-sdk-connector-parent-pom</artifactId>
   <version>0.8.0-RC4</version>
</parent>

<rest.sdk.commons.version>0.8.0-RC4</rest.sdk.commons.version>
<rest.sdk.mojo.version>0.8.0-RC4</rest.sdk.mojo.version>
----
. If you manually create the configuration class (`ConnectorNameConfiguration.java`) using the REST SDK override feature, you must add an extra annotation: 
+
[source,java,linenums]
----
import org.mule.sdk.api.annotation.JavaVersionSupport;
import org.mule.sdk.api.meta.JavaVersion;

@JavaVersionSupport({JavaVersion.JAVA_8, JavaVersion.JAVA_11, JavaVersion.JAVA_17})

public class YourConnectorConfiguration
----
. Regenerate the connector.

=== Upgrade a New Custom REST SDK Connector

If you generate a new connector using REST SDK and want to make that connector compatible with Java 17:

. Upgrade the REST SDK components and dependencies to version 0.8.0-RC4:
+
[source,xml,linenums]
----
<parent>
   <groupId>com.mulesoft.connectivity</groupId>
   <artifactId>rest-sdk-connector-parent-pom</artifactId>
   <version>0.8.0-RC4</version>
</parent>

<rest.sdk.commons.version>0.8.0-RC4</rest.sdk.commons.version>
<rest.sdk.mojo.version>0.8.0-RC4</rest.sdk.mojo.version>
---- 
. Upgrade the Mule runtime version to 4.6.x.

include::partial$partner-and-customer-guide.adoc[tags=rest-connect-connectors]
 
include::partial$partner-and-customer-guide.adoc[tags=test-custom-connector-mtf]

include::partial$partner-and-customer-guide.adoc[tags=communicate-support-level]

include::partial$partner-and-customer-guide.adoc[tags=see-also]
