= Pricing and Usage Metrics

[In progress]

MuleSoft offers a pricing and packaging model for Anypoint Platform that allots a number of Mule flows, Mule messages, and data throughput (measured as network I/O bytes). Not all types of Mule flows and messages count towards the allotments in a package. 

[[mule-flows]]
== Mule Flows

 A _Mule flow_ is a sequence of logical operations configured in XML using the `<flow>` element. A Mule app can consist of a single Mule Flow, or it can break up processing into discrete xref:mule-runtime::about-flows.adoc[Mule Flows and subflows] that you add to the app and connect together. Mule apps in production environments typically use multiple Mule Flows and subflows to divide the app into functional modules or for error-handling purposes. For example, one Mule flow might receive a record and transform data into a given format that another flow processes in some special way. 

=== Which Mule Message Scenarios Count towards your Anypoint Platform Package Allotment?

Only certain types of Mule flows count towards your allotment:
 
* Flows that contain a xref:mule-runtime::about-mule-event.adoc[Mule event source] 
* xref:apikit::index.adoc[Flows generated by APIkit] that are used to process API requests 

Mule flows are charged only when the application containing the Mule flow is deployed and running.

=== Mule Flow with an Event Source

The following Mule flow contains an event source as the first element. In this case, the `listener` counts towards your allotment.

[source,xml]
----
<flow name="test-flow" >
        <http:listener config-ref="cocheras-puerto-madero-api-httpListenerConfig" path="/daily-report"/>
         <logger level="INFO" message="#[output json --- attributes.queryParams]" />	
</flow>
----


=== Examples of Event Sources

[cols="2*",options="header"]
|===
| Connector | Source

| aggregators | aggregator-listener
| amqp | listener
| anypoint-mq | subscriber
.2+| apikit-odata | request-entity-collection-listener | request-entity-listener
.3+| as2-mule4 | as2-listener | as2-mdn-listener | non-repudiation-listener
| azure-service-bus-messaging | message-listener
| core | scheduler
| db | listener
.2+| email | listener-imap | listener-pop3
| file | listener
| ftp | listener
| ftps | listener
.3+| google-sheets | new-row-listener | new-spreadsheet-listener | updated-row-listener
| http | listener
| ibm-mq| listener
| jms | listener
.2+| kafka | batch-message-listener | message-listener
| mllp | mllp-listener
.4+| netsuite | deleted-object-listener | modified-object-listener | modified-record-listener | new-record-listener
| pubsub | message-listener
.7+| salesforce | deleted-object-listener | modified-object-listener | new-object-listener | replay-channel-listener | replay-topic-listener | subscribe-channel-listener | subscribe-topic-listener
.2+| sap | document-listener | function-listener
| servicebus | listener
| sftp | listener
| sockets | listener
.2+| solace | queue-listener | topic-listener
.2+| sqs | receive-messages | receivemessages
.3+| stripe | citizen-on-new-charge-listener | on-new-charge-listener | on-new-event-listener
| vm | listener
.2+| websocket | inbound-listener | outbound-listener
|===


[[mule-messages]]
== Mule Messages

A _Mule message_ is the data (the payload and its attributes) that passes through an application through one or more Mule flows.

=== Which Mule Message Scenarios Count towards your Anypoint Platform Package Allotment?

When an event source within a flow of a Mule application is triggered, the _event source_ (such as HTTP, Salesforce, scheduler, and so on) generates a Mule event that encapsulates a Mule message. The Mule message that is generated by the event source counts towards your Anypoint Platform package allotment. New instances of that message, which may be created during the processing of the original message as it moves through other processors in connected Mule flows, do not count towards your Anypoint Platform package allotment.

[[data-throughput]]
== Data Throughput
_Data Throughput_ is all the network I/O bytes produced by the infrastructure that starts and runs the Mule Runtime Server that runs a Mule Application. This includes the data that the application is producing to execute its business logic, as well as internal operational network traffic such as logs, health-checks, and monitoring traffic. For example, this includes inserting a record into a database and the network traffic associated to the infrastructure of the app such as Log forwarding, Control Plane connection, Monitoring metrics transfer.
