= Usage Reports
:page-aliases: gateway::flex-view-usage-reports.adoc

Usage reports provide comprehensive monthly and daily summaries that give you valuable insights into your resource use across Anypoint Platform products. By correlating your usage with billing cycles, you can gain insights into the factors influencing your costs, which enables you to proactively manage your budget and make informed decisions to optimize your resource allocation.

When you use an Anypoint Platform product that is metered, MuleSoft measures your usage and aggregates the records on a daily and monthly basis. Monthly and daily usage reports have a three-day latency, meaning that today’s usage is available in three days. All reports are calculated using the UTC time standard. For example, a daily usage is aggregated from 00:00 to 00:00 UTC. 

Daily usage retention is three months and monthly usage retention is up to five years.

Organizations that have a usage-based pricing model can compare actual usage from the report against the existing contract. However, usage reports are not for billing purposes. For more information about usage metrics and pricing, read xref:pricing.adoc[] and xref:usage-metrics.adoc[]

Some usage data, such as monthly statements and vCore allocation, appears in different areas of Anypoint Platform or Salesforce products. 

* Monthly statements for Mule runtime, including Mule flows, Mule messages, and data throughput are sent to the primary billing contact. 
+
xref:rpa-home::ms-automation-credits-usage-types.adoc[Automation credits] for RPA, Composer, Intelligent Document Processing (IDP), Salesforce Flow Orchestration, and MuleSoft for Flow are sent to the primary billing contact.
+
For more information, see https://help.salesforce.com/s/articleView?id=000390885&type=1[Monthly Account Summaries] documentation in Salesforce.

* Alerts for usage reaching 80% and 90% of the contractual entitlement are sent automatically to the primary billing contact email address. The primary billing contact gets alerts monthly once thresholds are reached.
+
For more information, see the https://help.salesforce.com/s/articleView?id=004811177&type=1[SalesforceUsage Alerts FAQ] knowledge article.

* Runtime Manager vCore allocation information and other metrics appear in Access Management.
+
For more information, see xref:pricing-metrics.adoc#runtime-manager-metrics[Runtime Manager Metrics].

Government Cloud and Anypoint Private Cloud Edition usages aren't available in usage reports.

[[products-usage-reports]]
== Products Available in Usage Reports

The following products are available in usage reports:

//* xref:mq::mq-usage.adoc[Anypoint MQ] (comment out until MQ GA release)
* Anypoint MQ
* API Experience Hub
* API Governance
* API Manager
* Flex Gateway
* Intelligent Document Processing (IDP)
* Mule Runtime
//* xref:object-store::osv2-usage.adoc[Object Store v2] (comment out until OS is released)
* Object Store v2

== Supported Mule Runtime Versions

include::partial$mule-runtime-metrics.adoc[tag=supportedRuntimes]
 

== Before You Begin

Usage reports are available only when you're signed in to the root organization and don't appear at the business group level.

To access usage reports, you need the xref:access-management::permissions-by-product.adoc#usage[Usage Viewer permission]. If you don't have this permission, contact your organization administrator to request access. The Usage Viewer permission must be xref:access-management::managing-permissions.adoc[applied at the root organization level] rather than the business group level. 


== Access Usage Reports

include::partial$usage-reports-tasks.adoc[tag=accessUsageReports]

[[export-usage-reports]]
== Export Usage Reports to a CSV File

You can export both daily and monthly usage reports to CSV files. These metrics match the data available in usage reports.

. Navigate to the usage report to download. 
. Click *Export as CSV*.

== Usage API
Use the Anypoint Usage API to programmatically access usage data. The API provides both daily and monthly details. Usage metrics are organized by business group and application. This provides detailed insight into product consumption. 

To use the API, see the API documentation for the https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a/usage-api/[Anypoint Usage API] for access and implementation details. Users must have Usage Viewer permission to access the Usage API.


[[usage-reports-on-hyperforce]]
== Usage Reports on Hyperforce
All features of Usage Reports are supported on Hyperforce.

== See Also

* xref:api-governance::index.adoc[]
* xref:api-manager::index.adoc[]
