= Usage Reports
:page-aliases: gateway::flex-view-usage-reports.adoc

Usage reports provide comprehensive monthly and daily summaries that give you valuable insights into your resource use across Anypoint Platform products. By correlating your usage with billing cycles, you can gain insights into the factors influencing your costs, which enables you to proactively manage your budget and make informed decisions to optimize your resource allocation.

When you use an Anypoint Platform product that is metered, MuleSoft measures your usage and aggregates the records on a daily and monthly basis. Monthly and daily usage reports have a three-day latency, meaning that today’s usage is available in three days. All reports are calculated using the UTC time standard. For example, a daily usage is aggregated from 00:00 to 00:00 UTC. 

Daily usage retention is three months and monthly usage retention is up to five years.

Organizations that have a usage-based pricing model can compare actual usage from the report against the existing contract. However, usage reports are not for billing purposes. For more information about usage metrics and pricing, read xref:pricing.adoc[] and xref:usage-metrics.adoc[]

Some usage data, such as monthly statements and vCore allocation, appears in different areas of Anypoint Platform or Salesforce products. 

* Monthly statements for Mule runtime, including Mule flows, Mule messages, and data throughput are sent to the primary billing contact. 
+
xref:rpa-home::ms-automation-credits-usage-types.adoc[Automation credits] for RPA, (Composer, Intelligent Document Processing (IDP), and API Experience Hub) are sent to the primary billing contact.
+
For more information, see https://help.salesforce.com/s/articleView?id=000390885&type=1[Monthly Account Summaries] documentation in Salesforce.
* Runtime Manager vCore allocation information and other metrics appear in Access Management.
+
For more information, see xref:pricing-metrics.adoc#runtime-manager-metrics[Runtime Manager Metrics].
* xref:mq::mq-usage.adoc#access-anypoint-mq-usage[Anypoint MQ] usage appears in Access Management.
+
For more information, see xref:pricing-metrics.adoc#mq-metrics[Anypoint MQ Metrics].
* xref:object-store::osv2-usage.adoc#access-object-store-effective-api-request-usage-charts[Object Store v2] usage appears in Access Management.
+
For more information, see xref:pricing-metrics.adoc#object-store-metrics[Object Store v2 Metrics].

[[products-usage-reports]]
== Products Available in Usage Reports

When you navigate to the *Usage Reports* page in Anypoint Platform, the selection of products you see varies based on the view you are using. Products that have only monthly usage reports are viewable only in the legacy usage reports view, while products that have both daily and monthly usage reports are available only in the new usage reports view. To switch between views, click the *Switch View* button in the banner. 

The following products have only monthly usage reports:

* API Manager

The following products have both daily and monthly usage reports:

* API Experience Hub
* API Governance
* Flex Gateway
* Mule Runtime
* Intelligent Document Processing (IDP)

== Supported Mule Runtime Versions

include::partial$mule-runtime-metrics.adoc[tag=supportedRuntimes]

include::partial$mule-runtime-metrics.adoc[tag=rtfApps] 

== Before You Begin

Usage reports are available only when you're signed in to the root organization and don't appear at the business group level.

To access usage reports, you need the xref:access-management::permissions-by-product.adoc#usage[Usage Viewer permission]. If you don't have this permission, contact your organization administrator to request access. The Usage Viewer permission must be xref:access-management::managing-permissions.adoc[applied at the root organization level] rather than the business group level. 

== Access Usage Reports

include::partial$usage-reports-tasks.adoc[tag=accessUsageReports]

== Export Usage Reports to a CSV File

You can export both daily and monthly usage reports to CSV files. These metrics match the data available in usage reports.

. Navigate to the usage report to download. 
. Click *Export as CSV*.


== See Also

* xref:api-governance::index.adoc[]
* xref:api-manager::index.adoc[]

