= Usage Reports
:page-aliases: gateway::flex-view-usage-reports.adoc

Usage reports provide comprehensive monthly and daily summaries that give you valuable insights into your resource use across Anypoint Platform products. By correlating your usage with billing cycles, you can gain insights into the factors influencing your costs. This enables you to proactively manage your budget and make informed decisions to optimize your resource allocation.

When you use an Anypoint Platform product that is metered, MuleSoft measures your usage and aggregates the records on a daily and monthly basis. 

Usage report data is refreshed twice a day. The most recent three days of data is subject to change. For example, on January 10, data from January 7 to January 10 might still be updated. Data from January 6 and earlier is final and won't change. 

All reports are calculated using the UTC time standard. For example, a daily usage is aggregated from 00:00 to 00:00 UTC. 

Daily usage retention is three months and monthly usage retention is up to five years.

Organizations that have a usage-based pricing model can compare actual usage from the report against the existing contract. However, usage reports are not for billing purposes. For more information about usage metrics and pricing, read xref:pricing.adoc[] and xref:usage-metrics.adoc[]

Some usage data, such as monthly statements and vCore allocation, appears in different areas of Anypoint Platform or Salesforce products. 

* Monthly statements for Mule runtime, including Mule flows, Mule messages, and data throughput are sent to the primary billing contact. 
+
xref:automation-credits-usage-and-rates.adoc[Automation credits] for RPA, Composer, Intelligent Document Processing (IDP), Salesforce Flow Orchestration, and MuleSoft for Flow are sent to the primary billing contact.
+
For more information, see https://help.salesforce.com/s/articleView?id=000390885&type=1[Monthly Account Summaries] documentation in Salesforce.

* Usage of certain Salesforce generative AI features (Agentforce and Einstein generative AI) or direct calls to the large language model (LLM) gateway consumes credits. All Salesforce AI usage from Anypoint Platform features is routed through your connected Salesforce org, which tracks consumption and handles billing.
+
Anypoint Platform features that use Einstein generative AI or Agentforce features include:
+
** Anypoint Code Builder
+
Use MuleSoft Dev Agent to develop integrations and API specs. 
+
For more information about this feature, see xref:anypoint-code-builder::int-ai-developing-integrations.adoc[] and xref:anypoint-code-builder::api-ai-design-spec.adoc[].
** Intelligent Document Processing (IDP)
+
Use Einstein generative AI to read and interpret documents.
+
For more information about this feature, see xref:idp::enhancing-data-extraction-with-einstein.adoc[]..
** Anypoint Exchange
+
Use Einstein generative AI to generate API documentation for REST APIs.
+
For more information about this feature, see xref:exchange::generating-documentation-with-ai.adoc[].
+
For more information about how the usage for these features is tracked and billed, see https://help.salesforce.com/s/articleView?id=ai.generative_ai_usage.htm&type=5[Agentforce and Generative AI Usage and Billing].

* Alerts for usage reaching 80% and 90% of the contractual entitlement are sent automatically to the primary billing contact email address. The primary billing contact gets alerts monthly once thresholds are reached.
+
For more information, see the https://help.salesforce.com/s/articleView?id=004811177&type=1[Salesforce Usage Alerts FAQ] knowledge article.

* Runtime Manager vCore allocation information and other metrics appear in Access Management.
+
For more information, see xref:pricing-metrics.adoc#runtime-manager-metrics[Runtime Manager Metrics].

Government Cloud and Anypoint Private Cloud Edition usages aren't available in usage reports.

[[products-usage-reports]]
== Products Available in Usage Reports

The following products are available in usage reports:

//* xref:mq::mq-usage.adoc[Anypoint MQ] (comment out until MQ GA release)
* Anypoint MQ
* API Experience Hub
* API Governance
* API Manager
* Omni Gateway
* Omni Gateway LLM Proxy
* Intelligent Document Processing (IDP)
* Mule Runtime
//* xref:object-store::osv2-usage.adoc[Object Store v2] (comment out until OS is released)
* Object Store v2

== Supported Mule Runtime Versions

include::partial$mule-runtime-metrics.adoc[tag=supportedRuntimes]
 

== Before You Begin

Usage reports are available only when you're signed in to the root organization and don't appear at the business group level.

To access usage reports, you need the xref:access-management::permissions-by-product.adoc#usage[Usage Viewer permission]. If you don't have this permission, contact your organization administrator to request access. The Usage Viewer permission must be xref:access-management::managing-permissions.adoc[applied at the root organization level] rather than the business group level. 


== Access Usage Reports

include::partial$usage-reports-tasks.adoc[tag=accessUsageReports]

[[export-usage-reports]]
== Export Usage Reports to a CSV File

You can export both daily and monthly usage reports to CSV files. These metrics match the data available in usage reports.

. Navigate to the usage report to download. 
. Click *Export as CSV*.

== Usage API
Use the Anypoint Usage API to programmatically access usage data. The API provides both daily and monthly details. Usage metrics are organized by business group and application. This provides detailed insight into product consumption. 

To use the API, see the API documentation for the https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a/usage-api/[Anypoint Usage API] for access and implementation details. Users must have Usage Viewer permission to access the Usage API.


[[usage-reports-on-control-planes]]
== Usage Reports on Control Planes
All features of Usage Reports are supported on Japan and Canada control planes.

== See Also

* xref:api-governance::index.adoc[]
* xref:api-manager::index.adoc[]
