= Viewing Usage Reports

Daily and monthly usage reports offer different metrics depending on the product you select. For more information about product metrics, see the xref:usage-metrics.adoc[Usage Metrics] documentation.

[[available-products]]
== Products Available in Usage Reports

The following products have only monthly usage reports and are available only in the legacy usage reports view:

* API Manager
* API governance

The following products have both daily and monthly usage reports and are available only in the new usage reports view:

* Mule Runtime
* API Experience Hub
* Flex Gateway

== Access Usage Reports

. Log in to Anypoint Platform using an account that has the Usage Viewer permission over your root organization.
. Click the circle with your organization name's initial in it and ensure you are at the root level of your organization and not in a business group.
. From the Anypoint Platform navigation bar, click your username icon.
. Click *Usage*.
. Select the product for which you want to view a usage report. +
If you do not see the product listed, click *Switch View*. +
. If applicable, click *Monthly Usage Report* or *Daily Usage Report*. +
Note that API Manager and API governance do not have daily usage reports.
. Select the month or day of the usage report you want to view. +
Only dates that Anypoint Platform collected data for the selected product are available.
+
The usage report appears, displaying an assortment of usage metrics that are xref:pricing-metrics.adoc[dependent on the product you selected]. 

== Export Usage Reports to CSV

You can export both daily and monthly usage reports to CSV files. When you open the CSV file from your exported usage report, a table appears, listing a table of metrics available for the product and time period you selected. These metrics match the data available in usage reports.

== Query Data using the Metering API and Anypoint Metric Query Language

Anypoint Platform offers the Metering API [link!] that enables you to access your usage data, which is stored in a domain-specific language. Using the Anypoint Monitoring Query Language [link!], you can construct simple, flexible, and secure queries to peruse your data. For more information, see [the Metering API link] and [the link to the subsection for the query language] in Exchange.

== Troubleshoot Usage Reports

Because platform data varies by the day, there might be instances in which usage reports are unavailable. 

[cols="^1,^1,^1"]
|===
| Problem | Explanation | Action Required

| I can't access the *Usage Reports* section in Anypoint Platform.
| You do not have the Usage Viewer permission, which is to view usage reports. 
| Contact your organization administrator to request Usage Viewer permission.

| When I open the product list to view a usage report, a supported product is not listed.
a| * Your current usage report view does not contain the product you want to view. For more information about product availability by view, see <<available-products>>.
* You do not have an active license for this product in Anypoint Platform.

a| * Switch views
* Review which products your organization is licensed to use.

| A month or day is unavailable in the date picker.
| Data is unavailable or not collected for this day or month.
| None

| After selecting a product and daily or monthly report in new usage reports, the report says `No Data`
| Data is unavailable or not collected for this day or month.
| None

| After selecting a month in legacy usage reports, the report says `No report available for this time period` instead of showing data.
| Data is unavailable or not collected for this month.
| None

|===