= Viewing Usage Reports

Daily and monthly usage reports offer different metrics depending on the product you select. For more information about product metrics, see the xref:usage-metrics.adoc[Usage Metrics] documentation.

[[available-products]]
== Products Available in Usage Reports

The following products have only monthly usage reports and are available only in the legacy usage reports view:

* API Manager
* API governance

The following products have both daily and monthly usage reports and are available only in the new usage reports view:

* Mule Runtime
* API Experience Hub
* Flex Gateway

== Access Usage Reports

include::partial$usage-reports-tasks.adoc[tag=accessUsageReports]

== Export Usage Reports to CSV

You can export both daily and monthly usage reports to CSV files. When you open the CSV file from your exported usage report, a table appears, listing a table of metrics available for the product and time period you selected. These metrics match the data available in usage reports.

include::partial$usage-reports-tasks.adoc[tag=accessUsageReports]

. Click *Export as CSV*.

== Query Data using the Metering API and Anypoint Metric Query Language

Anypoint Platform offers APIs that enable you to view your usage data and construct simple, flexible, and secure queries to peruse your data. For more information, see xref:usage-apis.adoc[usage APIs documentation] and the Metering API spec.

== Troubleshoot Usage Reports

Because platform data availability depends on activity in your organization, there might be instances in which usage reports are unavailable. 

|===
| Issue | Explanation | Action Required

| I can't access the *Usage Reports* section in Anypoint Platform.
| You do not have the Usage Viewer permission, which is to view usage reports. 
| Contact your organization administrator to request Usage Viewer permission.

| When I open the product list to view a usage report, a supported product is not listed.
a| * Your current usage report view does not contain the product you want to view. For more information about product availability by view, see <<available-products>>.
* You do not have an active license for this product in Anypoint Platform.

a| * Switch views
* Review which products your organization is licensed to use.

| A month or day is unavailable in the date picker.
| Data is unavailable or not collected for this day or month.
| None

| After selecting a product and daily or monthly report in new usage reports, the report says `No Data`
| Data is unavailable or not collected for this day or month.
| None

| After selecting a month in legacy usage reports, the report says `No report available for this time period` instead of showing data.
| Data is unavailable or not collected for this month.
| None

| A deployed Mule app is not listed in the Mule Runtime usage report.
| The Mule app is not a deployed to a supported version of Mule Runtime. For more information, see xref:mule-runtime-usage.adoc#supported-runtime-versions[supported runtime versions].
| Redeploy your apps with a supported runtime version, either manually or during a monthly patching cycle.

|===