= About Availability of the November Release
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:custom-product: Home
:custom-version: 
:custom-goal: Oops!
:noindex:

If the following applies to your Anypoint Platform Environment, then you have access to all new features of the November release:

* *New Anypoint Platform accounts created after November 18*: If you create a new trial account, you have access to all new features of the November release.

* *Anypoint Platform accounts (Customer, trial, and partner organizations) created before November 18 with no APIs in API Manager*: If you do not have APIs in API Manager, you have access to all the new features of the November release.

If your environment meets the above conditions, but you do not see the the environments in API Manager or the API Designer visual editor, contact your MuleSoft representative.

== See Also

* xref:1.0@design-center::index.adoc[About Design Center]
* xref:2.0@exchange::index.adoc[About Exchange]