= Getting Started with Anypoint Platform
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: getting started, how to, platform, mule, api
:noindex:

Welcome to the Getting Started section, where you can familiarize yourself with the most popular Anypoint Platform tools that support everything you do with APIs and integration applications. The documentation in this section helps you work toward building reusable code to manage integration of your digital assets. The key to integrating digital assets is the https://www.mulesoft.com/lp/whitepaper/api/api-led-connectivity[API-led approach].

[TIP]
If you have prior knowledge of APIs, you may want to know about xref:mule-runtime::index.adoc[Mule Runtime], MuleSoft's flagship integration platform. APIs can work with Mule applications in many ways. Try out xref:apikit::index.adoc[APIkit] or create a  https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[public developer portal] for customized access of APIs and other assets in your organization.

== Getting Started with APIs

. https://developer.mulesoft.com/guides/quick-start/designing-your-first-api[Design an API].
. xref:exchange::about-sharing-assets.adoc[Share an API].


== Getting Started with Mule Applications

. The documentation for Mule application development requires some familiarity with xref:studio::index.adoc[Anypoint Studio]. Make sure you have it installed.
. xref:mule-runtime::mule-app-tutorial.adoc[Create a Mule app with Studio].
. Use the xref:anypoint-connector.adoc[Anypoint Connector tutorial] to integrate with the Twitter service.

[TIP]
xref:mule-runtime::dataweave.adoc[DataWeave] is an essential tool that lets you weave complex data transformations into your Mule applications to quickly transform and map Mule message payloads to other data structures.

=== Getting Started with Deployment

Use Runtime Manager to xref:runtime-manager::deployment-strategies.adoc[deploy to your chosen target].

== Resources

* xref:exchange::index.adoc[Anypoint Exchange]
* xref:mule-runtime::index.adoc[Mule Runtime]
* xref:studio::index.adoc[Anypoint Studio]
* xref:api-manager::index.adoc[API Manager]
* Access xref:release-notes::index.adoc[Release Notes] for the release history of any MuleSoft product.
* https://anypoint.mulesoft.com/login/[Sign into Anypoint Platform]