// tag::intro[]
Mule runtime reports track your use of Mule messages, Mule flows, and data throughput. 

To track Mule message usage, the runtime report counts the number of times a Mule event source triggers a Mule message. You can view the number of these messages in a given day or month by business group, environment, and application. 

To calculate usage, MuleSoft meters and aggregates the number of messages daily and monthly. After a message is triggered, the report doesn't track changes to the message because the message is processed within the application’s flows.

A Mule flow is a sequence of logical operations configured within the XML `<flow/>` element of a Mule application. The runtime report tracks the Mule flows within a deployed and running Mule application that contains a Mule event source or APIkit route requests. This report doesn't track other Mule flows. You can view the maximum number of Mule flows in a given day or month in the usage report. 

To calculate usage, MuleSoft tracks the number of Mule flows for all business groups, environments, and applications. The maximum number of Mule flows within a day or month is identified based on the peak hour across the day or month. For the detailed breakdown, MuleSoft shows the peak hour usage per business group, environment, and application. 

Data throughput is the network I/O bytes produced by the infrastructure that runs the Mule runtime engine running the Mule application. 

To calculate usage, MuleSoft tracks GB usage and aggregates the total daily and monthly GBs.
// end::intro[]

== Requirements for Mule Runtime to Report Usage

// tag::supportedRuntimes[]

include::partial$usage-runtime.adoc[]

You must redeploy your apps with a supported version, either manually or during the monthly patching cycle. The monthly patching cycle is applicable only for CloudHub and CloudHub 2.0 applications. 

You can xref:cloudhub-2::ch2-update-apps.adoc#roll-back-to-a-previous-successful-configuration[roll back] to a previous successful application configuration. However, if an app is using a Mule version not supported by usage reports, you must choose a compliant Mule version before deploying changes. After deployment, a new configuration with the previously chosen settings and a supported runtime is created.

// end::supportedRuntimes[]

// tag::cards[]

Total Data Throughput::
The sum of data in gigabytes (GB) transmitted across all Mule apps and business groups during the selected time period. For more information about how this metric is billed, see xref:usage-metrics.adoc#data-throughput[data throughput].  

|Data Graph	
|_DataGraph orchestration_: An API request made by Anypoint DataGraph to the source APIs to get data for the GraphQL API request made to Anypoint DataGraph. 
|Orchestrations are not currently aggregated on usage reports.

|IDP 
|_Intelligent Document Processing (IDP) Document Pages_: A single page processed by IDP.
|IDP document actions might process documents that have more than one page, with each page counting separately. When RPA executes document actions, it also counts towards document pages and additionally consumes the corresponding RPA Bot Minutes, accounting for the time the RPA process runs. 
|===

Max Flows::
The maximum number of concurrent flows across all Mule apps and business groups during the selected time period. For more information about how this metric is billed, see xref:usage-metrics.adoc#mule-flows[Mule flows].  

// end::cards[]

// tag::table[]

Select the *Business Group Details* tab to view:

[%header%autowidth.spread]
|===
|Business Group 
|The business group a Mule app is deployed to

|Environment Type
|The environment in which a Mule app is deployed.

| Cluster
|
|Cluster Capacity (Millicores)
|
|===

Select the *Application Details* tab to view:

|Application
|The name of the Mule application.

| Business Group
| The business group a Mule app is deployed to.

| Deployment Type
| The runtime plane to which the Mule app is deployed. CloudHub (abbreviated as CH), CloudHub 2.0 (abbreviated as CH2), and Runtime Fabric (abbreviated as RTF) are supported. 

|Environment Type
|The environment in which a Mule app is deployed.

| Cluster
| The name of the cluster containing the replicas and worker nodes.

| CPU Limit
| The maximum amount of vCPU the application can use. This is shared CPU on the worker node.

| CPU Reserve (Millicores)
| The amount of vCPU guaranteed to the application and reserved for its use.

| Mule Flows 
| The sum of flows in the Mule app. This number is calculated by multiplying flows by the number of workers (CloudHub) or replicas (CloudHub 2.0). For more information about how this metric is billed, see xref:usage-metrics.adoc#mule-flows[Mule flows].

| Mule Messages
| The sum of inbound and outbound Mule messages in the Mule app. For more information about how this metric is billed, see xref:usage-metrics.adoc#mule-messages[Mule messages].  

| Data Throughput (GB)
| The sum of inbound and outbound data in gigabytes (GB) transmitted by the Mule app. For more information about how this metric is billed, see xref:usage-metrics.adoc#data-throughput[data throughput].  

// end::table[]

// tag::flows[]
== Mule Flows

A _Mule flow_ is a sequence of logical operations configured in XML by using the `<flow>` element. A Mule app can consist of a single Mule flow, or it can break up processing into discrete xref:mule-runtime::about-flows.adoc[Mule flows and subflows] that you add to the app and connect together. Mule apps in production environments typically use multiple Mule flows and subflows to divide the app into functional modules or for error-handling purposes. For example, one Mule flow might receive a record and transform data into a given format that another flow processes. 

In a usage report, flow counts are calculated by multiplying the number of flows in an app by the number of workers (CloudHub) or replicas (Runtime Fabric and CloudHub 2.0).
// end::flows[]

// tag::billableFlows[]
=== Mule Flow Scenarios that Count Towards Your Anypoint Platform Package Allotment

The following Mule flows count towards your allotment:
 
* Flows that contain a xref:mule-runtime::about-mule-event.adoc[Mule event source] 
* xref:apikit::index.adoc[Flows generated by APIkit] that process API requests 

Mule flows are charged only when the application containing the Mule flow is deployed and running. 

=== Mule Flow with an Event Source

The following Mule flow contains an event source as the first element. In this case, the `listener` counts towards your allotment.

[source,xml]
----
<flow name="test-flow" >
        <http:listener config-ref="cocheras-puerto-madero-api-httpListenerConfig" path="/daily-report"/>
         <logger level="INFO" message="#[output json --- attributes.queryParams]" />	
</flow>
----

=== Examples of Event Sources

[cols="2*",options="header"]
|===
| Connector | Source

| aggregators | aggregator-listener
| amqp | listener
| anypoint-mq | subscriber
.2+| apikit-odata | request-entity-collection-listener | request-entity-listener
.3+| as2-mule4 | as2-listener | as2-mdn-listener | non-repudiation-listener
| azure-service-bus-messaging | message-listener
| core | scheduler
| db | listener
.2+| email | listener-imap | listener-pop3
| file | listener
| ftp | listener
| ftps | listener
.3+| google-sheets | new-row-listener | new-spreadsheet-listener | updated-row-listener
| http | listener
| ibm-mq| listener
| jms | listener
.2+| kafka | batch-message-listener | message-listener
| mllp | mllp-listener
.4+| netsuite | deleted-object-listener | modified-object-listener | modified-record-listener | new-record-listener
| pubsub | message-listener
.7+| salesforce | deleted-object-listener | modified-object-listener | new-object-listener | replay-channel-listener | replay-topic-listener | subscribe-channel-listener | subscribe-topic-listener
.2+| sap | document-listener | function-listener
| servicebus | listener
| sftp | listener
| sockets | listener
.2+| solace | queue-listener | topic-listener
.2+| sqs | receive-messages | receivemessages
.3+| stripe | citizen-on-new-charge-listener | on-new-charge-listener | on-new-event-listener
| vm | listener
.2+| websocket | inbound-listener | outbound-listener
|===


// Example Use-case [1 Mule flow]: A CSV file with customer contacts needs to be uploaded to CRM on a regularly scheduled basis

// image

// Using a single Mule flow with four elements, this application accepts CSV files that contain contact information, and then uploads the contacts to MS Dynamics. The Mule flow accepts a CSV file by polling a local folder at frequent intervals that are set with a Scheduler (event source) component. 

// The columns of the CSV file contain selected contact information, such as first name, last name, phone number, and email. These columns are mapped to each of the respective fields in a specific Dynamics CRM account, and the rows are uploaded.

=== Mule Flow Generated by APIkit and Used for Routing APIkit Requests

APIkit is a tool that simplifies the implementation of APIs by automatically generating a minimal set of Mule flows based on the API specification. Each APIkit router endpoint counts as a distinct Mule flow. These Mule flows do not have an event source and are used for the handling of HTTP requests for a particular API method and path.

==== Example of an APIkit Request:

This flow routes APIkit requests and handles the GET request in the `/reservation` path:

[source,xml]
----
<flow name="get:\reservation:cocheras-puerto-madero-api-config">
        <logger level="INFO" message="#[output json --- attributes.queryParams]" />
</flow>
----

// Example Use-case [12 flows]: New customer profile data needs to be moved from Marketing Cloud to Master Data Management (MDM) 

// Mule Flow with Event Source [1]: Main Mule Flow with the HTTP listener that routes message to appropriate flow generated by APIkit based on the message content.

// image 

// Mule Flows used for routing APIkit Requests [11]:

// image

// end::billableFlows[]

// tag::nonBillableFlows[]
[[non-billable-flows]]
=== Mule Flows That Don't Count Against Your Anypoint Platform Package Allotment 

Mule flows that don't have an event source and aren't used for routing APIkit requests aren’t charged against your Anypoint Platform package allotment. These Mule flows are primarily used to modularize code.

Example:

[source,xml]
----
2.a - Flow with only a logger component
<flow name="just-logging">
        <logger level="INFO" message="#[output json --- attributes.queryParams]" />
</flow>
----
// end::nonBillableFlows[]

// tag::muleMessages[]
[[mule-messages]]
== Mule Messages

A _Mule message_ is the data (the payload and its attributes) that passes through one or more Mule flows in an application. A Mule message is part of a Mule event, which is generated when the event source within a Mule flow is triggered. For example, a Mule event that consists of a Mule message is created when an HTTP listener receives a request or each time the scheduler component triggers an execution of the Mule flow. 
Mule message processors in a Mule flow (such as core components, file read operations, or the HTTP request operations) can then retrieve, set, and process Mule message data that resides in the Mule event according to their configurations. 
A Mule message is immutable, so every change to a Mule message results in the creation of a new instance. Each processor in a flow that receives a Mule message returns a new Mule message that consists of a message payload (the body of the message) and message attributes (metadata associated with the message).

[[billable-mule-messages]]
=== Mule Message Scenarios that Count Towards Your Anypoint Platform Package Allotment

When an event source within a flow of a Mule application is triggered, the _event source_ (such as HTTP, Salesforce, scheduler, and so on) generates a Mule event that encapsulates a Mule message. The Mule message generated by the event source counts towards your Anypoint Platform package allotment. New instances of that message, which can be created during the processing of the original message as it moves through other processors in connected Mule flows, do not count towards your Anypoint Platform package allotment.

// add the three missing examples

// end::muleMessages[]

// tag::dataThroughput[]
[[data-throughput]]
== Data Throughput

_Data Throughput_ is all of the network I/O bytes produced by the infrastructure that starts and runs the Mule Runtime server that runs a Mule application. This includes the data that the application produces to execute its business logic, as well as internal operational network traffic such as logs, health-checks, and monitoring traffic. For example, data throughput includes inserting a record into a database and the network traffic associated with the infrastructure of the app, such as log forwarding, control plane connection, and monitoring metrics transfer. 

// end::dataThroughput[]
