// tag::intro[]
Mule runtime reports track your use of Mule messages, Mule flows, and data throughput. 

To track Mule message usage, the runtime report counts the number of times a Mule event source triggers a Mule message. You can view the number of these messages in a given day or month by business group, environment, and application. 

To calculate usage, MuleSoft meters and aggregates the number of messages on a daily and monthly basis. After a message is triggered, the report does not track changes to the message because the message is processed within the application’s flows.

A Mule flow is a sequence of logical operations configured within the XML `<flow/>` element of a Mule application. The runtime report tracks the Mule flows within a deployed and running Mule application that contains a Mule event source or APIkit route requests. This report doesn't track other Mule flows. You can view the maximum number of Mule flows in a given day or month in the usage report. 

To calculate usage, MuleSoft tracks the number of Mule flows for all business groups, environments, and applications. The maximum number of Mule flows within a day or month is identified based on the peak hour across the day or month. For the detailed breakdown, MuleSoft shows the peak hour usage per business group, environment, and application. 

Data throughput is all the network I/O bytes produced by the infrastructure that starts and runs the Mule runtime engine that runs a Mule application. You can view the total amount of GB usage in a given day or month by business group, environment, and application. 

To calculate usage, MuleSoft tracks GB usage and aggregates the total GBs on a daily and monthly basis.
// end::intro[]

// tag::supportedRuntimes[]

include::partial$usage-runtime.adoc[]

You must redeploy your apps with a supported version, either manually or during the monthly patching cycle. The monthly patching cycle is applicable only for CloudHub and CloudHub 2.0 applications. 

To xref:cloudhub-2::ch2-update-apps.adoc#roll-back-to-a-previous-successful-configuration[roll back] to a previous successful configuration of existing applications that use a Mule version that usage reports don't support, you must choose a compliant version before deploying changes. After deployment, a new configuration with the previously chosen settings and a supported runtime is created.

// end::supportedRuntimes[]

// tag::rtfApps[]
If usage reports don't display data from Runtime Fabric apps, ensure the following requirements are met:

* You're using Runtime Fabric agent version 1.13.112, 2.1.30, or later. 
* After updating the Runtime Fabric agent, you manually redeployed each Runtime Fabric app with a supported date-patch version.

If you're still missing Runtime Fabric apps in your usage reports, contact your account executive to request a report of apps that are not upgraded and what actions need to be taken to update them.
// end::rtfApps[]

// tag::cards[]

Total Data Throughput::
The sum of data in gigabytes (GB) transmitted across all Mule apps and business groups during the selected time period. For more information about how this metric is billed, see xref:usage-metrics.adoc#data-throughput[data throughput].  

Total Mule Messages:: 
The sum of all Mule messages transmitted across all Mule apps and business groups during the selected time period. For more information about how this metric is billed, see xref:usage-metrics.adoc#mule-messages[Mule messages].  

Max Flows::
The maximum number of concurrent flows across all Mule apps and business groups during the selected time period. For more information about how this metric is billed, see xref:usage-metrics.adoc#mule-flows[Mule flows].  

// end::cards[]

// tag::table[]
Business Group:: 
The business group in which a Mule app is deployed.

Environment:: 
The environment in which a Mule app is deployed.

Application::
The name of the Mule application.

Deployment:: 
The runtime plane to which the Mule app is deployed. CloudHub (abbreviated as CH), CloudHub 2.0 (abbreviated as CH2), and Runtime Fabric (abbreviated as RTF) are supported. 

Flows:: 
The sum of flows in the Mule app. This number is calculated by multiplying flows by the number of workers (CloudHub) or replicas (CloudHub 2.0). For more information about how this metric is billed, see xref:usage-metrics.adoc#mule-flows[Mule flows].

Messages::
The sum of inbound and outbound Mule messages in the Mule app. For more information about how this metric is billed, see xref:usage-metrics.adoc#mule-messages[Mule messages].  

Data Throughput::
The sum of inbound and outbound data in gigabytes (GB) transmitted by the Mule app. For more information about how this metric is billed, see xref:usage-metrics.adoc#data-throughput[data throughput].  

Number of Workers::
The sum of all workers (CloudHub) or replicas (CloudHub 2.0) of a Mule app. Apps that do not have workers or replicas display a value of `N/A` in this column.
// end::table[]

// tag::flows[]
== Mule Flows

A _Mule flow_ is a sequence of logical operations configured in XML by using the `<flow>` element. A Mule app can consist of a single Mule flow, or it can break up processing into discrete xref:mule-runtime::about-flows.adoc[Mule flows and subflows] that you add to the app and connect together. Mule apps in production environments typically use multiple Mule flows and subflows to divide the app into functional modules or for error-handling purposes. For example, one Mule flow might receive a record and transform data into a given format that another flow processes. 

In a usage report, flow counts are calculated by multiplying the number of flows in an app by the number of workers (CloudHub) or replicas (Runtime Fabric and CloudHub 2.0).
// end::flows[]

// tag::billableFlows[]
=== Mule Flow Scenarios that Count Towards Your Anypoint Platform Package Allotment

The following Mule flows count towards your allotment:
 
* Flows that contain a xref:mule-runtime::about-mule-event.adoc[Mule event source] 
* xref:apikit::index.adoc[Flows generated by APIkit] that process API requests 

Mule flows are charged only when the application containing the Mule flow is deployed and running. 

=== Mule Flow with an Event Source

The following Mule flow contains an event source as the first element. In this case, the `listener` counts towards your allotment.

[source,xml]
----
<flow name="test-flow" >
        <http:listener config-ref="cocheras-puerto-madero-api-httpListenerConfig" path="/daily-report"/>
         <logger level="INFO" message="#[output json --- attributes.queryParams]" />	
</flow>
----


=== Examples of Event Sources

[cols="2*",options="header"]
|===
| Connector | Source

| aggregators | aggregator-listener
| amqp | listener
| anypoint-mq | subscriber
.2+| apikit-odata | request-entity-collection-listener | request-entity-listener
.3+| as2-mule4 | as2-listener | as2-mdn-listener | non-repudiation-listener
| azure-service-bus-messaging | message-listener
| core | scheduler
| db | listener
.2+| email | listener-imap | listener-pop3
| file | listener
| ftp | listener
| ftps | listener
.3+| google-sheets | new-row-listener | new-spreadsheet-listener | updated-row-listener
| http | listener
| ibm-mq| listener
| jms | listener
.2+| kafka | batch-message-listener | message-listener
| mllp | mllp-listener
.4+| netsuite | deleted-object-listener | modified-object-listener | modified-record-listener | new-record-listener
| pubsub | message-listener
.7+| salesforce | deleted-object-listener | modified-object-listener | new-object-listener | replay-channel-listener | replay-topic-listener | subscribe-channel-listener | subscribe-topic-listener
.2+| sap | document-listener | function-listener
| servicebus | listener
| sftp | listener
| sockets | listener
.2+| solace | queue-listener | topic-listener
.2+| sqs | receive-messages | receivemessages
.3+| stripe | citizen-on-new-charge-listener | on-new-charge-listener | on-new-event-listener
| vm | listener
.2+| websocket | inbound-listener | outbound-listener
|===


// Example Use-case [1 Mule flow]: A CSV file with customer contacts needs to be uploaded to CRM on a regularly scheduled basis

// image

// Using a single Mule flow with four elements, this application accepts CSV files that contain contact information, and then uploads the contacts to MS Dynamics. The Mule flow accepts a CSV file by polling a local folder at frequent intervals that are set with a Scheduler (event source) component. 

// The columns of the CSV file contain selected contact information, such as first name, last name, phone number, and email. These columns are mapped to each of the respective fields in a specific Dynamics CRM account, and the rows are uploaded.

=== Mule Flow Generated by APIkit and Used for Routing APIkit Requests

APIkit is a tool that simplifies the implementation of APIs by automatically generating a minimal set of Mule flows based on the API specification. Each APIkit router endpoint counts as a distinct Mule flow. These Mule flows do not have an event source and are used for the handling of HTTP requests for a particular API method and path.

==== Example of an APIkit Request:

This flow routes APIkit requests and handles the GET request in the `/reservation` path:

[source,xml]
----
<flow name="get:\reservation:cocheras-puerto-madero-api-config">
        <logger level="INFO" message="#[output json --- attributes.queryParams]" />
</flow>
----

// Example Use-case [12 flows]: New customer profile data needs to be moved from Marketing Cloud to Master Data Management (MDM) 

// Mule Flow with Event Source [1]: Main Mule Flow with the HTTP listener that routes message to appropriate flow generated by APIkit based on the message content.

// image 

// Mule Flows used for routing APIkit Requests [11]:

// image

// end::billableFlows[]

// tag::nonBillableFlows[]
[[non-billable-flows]]
=== Mule Flows that Don't Count Against Your Anypoint Platform Package Allotment 

Mule Flows that don't have an event source and aren't used for the routing of APIkit requests are not charged against your Anypoint Platform package allotment. These are Mule flows primarily used to modularize code.

Example:

[source,xml]
----
2.a - Flow with only a logger component
<flow name="just-logging">
        <logger level="INFO" message="#[output json --- attributes.queryParams]" />
</flow>
----
// end::nonBillableFlows[]

// tag::muleMessages[]
[[mule-messages]]
== Mule Messages

A _Mule message_ is the data (the payload and its attributes) that passes through one or more Mule flows in an application. A Mule message is part of a Mule event, which is generated when the event source within a Mule flow is triggered. For example, a Mule event that consists of a Mule message is created when an HTTP listener receives a request or each time the scheduler component triggers an execution of the Mule flow. 
Mule message processors in a Mule flow (such as core components, file read operations, or the HTTP request operations) can then retrieve, set, and process Mule message data that resides in the Mule event according to their configurations. 
A Mule message is immutable, so every change to a Mule message results in the creation of a new instance. Each processor in a flow that receives a Mule message returns a new Mule message that consists of a message payload (the body of the message) and message attributes (metadata associated with the message).

[[billable-mule-messages]]
=== Mule Message Scenarios that Count Towards Your Anypoint Platform Package Allotment

When an event source within a flow of a Mule application is triggered, the _event source_ (such as HTTP, Salesforce, scheduler, and so on) generates a Mule event that encapsulates a Mule message. The Mule message generated by the event source counts towards your Anypoint Platform package allotment. New instances of that message, which can be created during the processing of the original message as it moves through other processors in connected Mule flows, do not count towards your Anypoint Platform package allotment.

// add the three missing examples

// end::muleMessages[]

// tag::dataThroughput[]
[[data-throughput]]
== Data Throughput

_Data Throughput_ is all of the network I/O bytes produced by the infrastructure that starts and runs the Mule Runtime server that runs a Mule application. This includes the data that the application produces to execute its business logic, as well as internal operational network traffic such as logs, health-checks, and monitoring traffic. For example, data throughput includes inserting a record into a database and the network traffic associated with the infrastructure of the app, such as log forwarding, control plane connection, and monitoring metrics transfer. 

// end::dataThroughput[]