//The SimpleReference template covers reference information. Copy this template into an .adoc file and remove the optional elements you don’t need. 

= Page Title
////
For reference page and topic titles, use a noun phrase that describes the content: Logical Operators or HTTPS Send Configuration

Add 1-2 introductory sentences that provide an overview of the 
topic—what it is and why the reader cares. If relevant, mention 
specific tasks that require this information.
////

== Reference Topic (Heading is optional if reference is short)
////

If using heading, add 1-2 sentences to introduce reference

Must contain: list or table of items or code examples
Must not contain: steps or conceptual narrative
Can contain ===

Note: When possible avoid headings like “Notes” for columns in reference tables. Aim for a specific column heading that explains the function of the notes. Alternatively, if they’re short and scannable, add notes that don’t fit a column as notes within the relevant cell.

[%header%autowidth.spread]

|===
|Column Title |Column Title |Column Title
|entry 1      |entry 2      |entry 3
|===
////


// == (Optional) Reference Topic

// == (Optional) Related Resources
////
Note: Do not change heading

Don’t use this section as filler. Link only to relevant related info and not just any info that is “kinda” related.

Must contain: unordered list
* xref:file-name.adoc[link-text]
* xref:file-name.adoc#paragraph-target[link text]
* xref:repo-name::filename.adoc[link text]
* https://www.url.com[link-text^]
////
