//The SimpleTask template covers one set or steps used to complete a task. Copy this template into an .adoc file and remove the optional elements you don’t need. 

= Page Title 
////
For page titles, use imperative verbs and plural nouns(unless it’s incorrect to do so), for example: Deploy Applications to Runtime Manager, Set Up Projects in Studio, Upgrade Runtime Fabric, and so on.

Add 1-2 introductory sentences that provide an overview of the task—what it is and why the reader cares. Concepts in support of a task tell what a task is and its purpose in the user environment. 

If you can do this in a few sentences for the task, you can omit the concept topic. Otherwise, provide an introduction that is fully developed in a separate Concept topic in the same doc set as the task.
////

// == Task Topic (Heading is optional if task is short)
////
For Task Topic, use imperative verbs and singular nouns, for example: Deploy an Application to Runtime Manager, Set Up A Project in Studio, Upgrade Runtime Fabric, and so on.
////

== Before You Begin
////

Note: Do not change heading

Add introductory phrase to prerequisite list, followed by a 
colon and a list of items in parallel construction, for example:  

Before getting started, ensure that you have:

* Familiarity with Anypoint Platform and Exchange, including    permissions to use Exchange to publish and view RAML or OAS specifications in your business group
* An Anypoint Platform account
* Admin or Contribute permissions

OR

To add an API to the unified schema, ensure that you have:

* Created a REST API using either a RAML or OAS specification
* Published the API in Exchange in the same organization as your unified schema
* Initiated an instance of the API with an accessible URL

OR

Your <product> installation must meet the following hardware and software requirements.

If the list of requirements is simple, remove the headings and use an unordered list.

=== Hardware Requirements

*
*
*

=== Software Requirements

*
*
*

Note: Some products/features might require documenting extensive requirements for installation. In such cases, use a reference topic that links to the installation tasks and vice versa. 

Add any permissions, version numbers, or tools needed 
Must contain: ordered or unordered list or a table
Can contain links to external information where necessary
Can contain tables with version numbers, permissions, and so on 
////

////
Start task steps:
If necessary, add intro phrase: To <complete task>:

When possible, use a navigational starting point.

. Navigate to *here* > *here* > *here*.


OR

. From <starting point>, <perform this first action>.
. 
. 


(Optional) After the task, add 1-2 sentences to indicate expected results or next steps. 
////

////
== (Optional) Related Resources
 
Note: Do not change heading

Don’t use this section as filler. Link only to relevant related info and not just any info that is “kinda” related.

Must contain: unordered list
* xref:file-name.adoc[link-text]
* xref:file-name.adoc#paragraph-target[link text]
* xref:repo-name::filename.adoc[link text]
* https://www.url.com[link-text^]
////

