name: reviewdog
on: [ push, pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Vale (push)
      if: github.ref != "refs/pull/**/merge"
      uses: errata-ai/vale-action@reviewdog
      with:
        version: 2.17.0
        fail_on_error: true
        reporter: local
      env:
        # Required, set by GitHub actions automatically:
        # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Vale (PR)
      if: github.ref == "refs/pull/**/merge"
      uses: errata-ai/vale-action@reviewdog
      with:
        version: 2.17.0
        fail_on_error: false
      env:
        # Required, set by GitHub actions automatically:
        # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
