name: Linting
on: [ pull_request, push ]
jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get latest version
      id: style_version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: mulesoft/dev-docs-writing-style
    - name: Download and extract
      if: ${{ github.event_name == 'pull_request' }}
      uses: schmiddim/action-wget-unzip@v2
      with:
        url: https://github.com/mulesoft/dev-docs-writing-style/releases/download/${{ steps.style_version.outputs.release }}/Mulesoft.zip
        destination: ../dev-docs-writing-style/Mulesoft
    - name: Vale
      if: ${{ github.event_name == 'pull_request' }}
      uses: errata-ai/vale-action@reviewdog
      with:
        version: 2.17.0
      env:
        # Required, set by GitHub actions automatically:
        # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    # - name: Vale
    #   uses: errata-ai/vale-action@v1
    #   with:
    #     styles: |
    #       https://github.com/mulesoft/dev-docs-writing-style/releases/download/${{ steps.style_version.outputs.release }}/Mulesoft.zip
    #   env:
    #     # Required, set by GitHub actions automatically:
    #     # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
    #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}