name: Linting
on: [ pull_request, push ]
jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get latest release version
      id: style_version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        excludes: prerelease, draft
        repository: mulesoft/dev-docs-writing-style
    - name: Download and extract
      if: ${{ github.event_name == 'pull_request' }}
      uses: schmiddim/action-wget-unzip@v2
      with:
        url: https://github.com/mulesoft/dev-docs-writing-style/releases/download/${{steps.style_version.outputs.release}}/Mulesoft.zip
        destination: .github/Mulesoft
    - name: Vale (pr)
      if: ${{ github.event_name == 'pull_request' }}
      uses: errata-ai/vale-action@reviewdog
      with:
        version: 2.17.0
        fail_on_error: false
      env:
        # Required, set by GitHub actions automatically:
        # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Vale (push)
      if: ${{ github.event_name != 'pull_request' }}
      uses: errata-ai/vale-action@reviewdog
      with:
        version: 2.17.0
      env:
        fail_on_error: true
        # Required, set by GitHub actions automatically:
        # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
